/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 05:05:28 GMT 2024
 */

package br.com.swconsultoria.nfe.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.swconsultoria.nfe.schema.envConfRecebto.TRetEnvEvento;
import br.com.swconsultoria.nfe.schema.retConsCad.TRetConsCad;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TRetEnviNFe;
import br.com.swconsultoria.nfe.schema_4.inutNFe.TRetInutNFe;
import br.com.swconsultoria.nfe.schema_4.retConsReciNFe.TRetConsReciNFe;
import br.com.swconsultoria.nfe.util.RetornoUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RetornoUtil_ESTest extends RetornoUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      // Undeclared exception!
      try { 
        RetornoUtil.validaManifestacao((TRetEnvEvento) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TRetInutNFe tRetInutNFe0 = new TRetInutNFe();
      // Undeclared exception!
      try { 
        RetornoUtil.validaInutilizacao(tRetInutNFe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      try { 
        RetornoUtil.validaEpec((br.com.swconsultoria.nfe.schema.envEpec.TRetEnvEvento) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TRetConsCad tRetConsCad0 = new TRetConsCad();
      // Undeclared exception!
      try { 
        RetornoUtil.validaConsultaCadastro(tRetConsCad0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        RetornoUtil.validaCartaCorrecao((br.com.swconsultoria.nfe.schema.envcce.TRetEnvEvento) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        RetornoUtil.validaCancelamentoSubstituicao((br.com.swconsultoria.nfe.schema.envEventoCancSubst.TRetEnvEvento) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        RetornoUtil.validaCancelamento((br.com.swconsultoria.nfe.schema.envEventoCancNFe.TRetEnvEvento) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      // Undeclared exception!
      try { 
        RetornoUtil.validaAssincrono(tRetConsReciNFe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      // Undeclared exception!
      try { 
        RetornoUtil.isRetornoAssincrono(tRetEnviNFe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("104");
      // Undeclared exception!
      try { 
        RetornoUtil.validaSincrono(tRetEnviNFe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("102");
      try { 
        RetornoUtil.validaSincrono(tRetEnviNFe0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 102 - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("103");
      // Undeclared exception!
      try { 
        RetornoUtil.validaSincrono(tRetEnviNFe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setCStat("128");
      try { 
        RetornoUtil.validaAssincrono(tRetConsReciNFe0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 128 - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setCStat("104");
      RetornoUtil.validaAssincrono(tRetConsReciNFe0);
      assertNull(tRetConsReciNFe0.getDhRecbto());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("Q7M\",rBvB`p1BP");
      try { 
        RetornoUtil.isRetornoAssincrono(tRetEnviNFe0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Q7M\",rBvB`p1BP - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("104");
      boolean boolean0 = RetornoUtil.isRetornoAssincrono(tRetEnviNFe0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("103");
      boolean boolean0 = RetornoUtil.isRetornoAssincrono(tRetEnviNFe0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TRetInutNFe tRetInutNFe0 = new TRetInutNFe();
      TRetInutNFe.InfInut tRetInutNFe_InfInut0 = new TRetInutNFe.InfInut();
      tRetInutNFe_InfInut0.setCStat("302");
      tRetInutNFe0.setInfInut(tRetInutNFe_InfInut0);
      try { 
        RetornoUtil.validaInutilizacao(tRetInutNFe0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 302 - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TRetConsCad tRetConsCad0 = new TRetConsCad();
      TRetConsCad.InfCons tRetConsCad_InfCons0 = new TRetConsCad.InfCons();
      tRetConsCad_InfCons0.setCStat("103");
      tRetConsCad0.setInfCons(tRetConsCad_InfCons0);
      try { 
        RetornoUtil.validaConsultaCadastro(tRetConsCad0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 103 - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TRetConsCad tRetConsCad0 = new TRetConsCad();
      TRetConsCad.InfCons tRetConsCad_InfCons0 = new TRetConsCad.InfCons();
      tRetConsCad_InfCons0.setCStat("111");
      tRetConsCad0.setInfCons(tRetConsCad_InfCons0);
      RetornoUtil.validaConsultaCadastro(tRetConsCad0);
      assertNull(tRetConsCad0.getVersao());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      br.com.swconsultoria.nfe.schema.envEpec.TRetEnvEvento tRetEnvEvento0 = new br.com.swconsultoria.nfe.schema.envEpec.TRetEnvEvento();
      try { 
        RetornoUtil.validaEpec(tRetEnvEvento0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // null - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      br.com.swconsultoria.nfe.schema.envEpec.TRetEnvEvento tRetEnvEvento0 = new br.com.swconsultoria.nfe.schema.envEpec.TRetEnvEvento();
      tRetEnvEvento0.setCStat("128");
      RetornoUtil.validaEpec(tRetEnvEvento0);
      assertNull(tRetEnvEvento0.getIdLote());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      br.com.swconsultoria.nfe.schema.envcce.TRetEnvEvento tRetEnvEvento0 = new br.com.swconsultoria.nfe.schema.envcce.TRetEnvEvento();
      try { 
        RetornoUtil.validaCartaCorrecao(tRetEnvEvento0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // null - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      br.com.swconsultoria.nfe.schema.envcce.TRetEnvEvento tRetEnvEvento0 = new br.com.swconsultoria.nfe.schema.envcce.TRetEnvEvento();
      tRetEnvEvento0.setCStat("128");
      RetornoUtil.validaCartaCorrecao(tRetEnvEvento0);
      assertNull(tRetEnvEvento0.getVersao());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      try { 
        RetornoUtil.validaManifestacao(tRetEnvEvento0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // null - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      br.com.swconsultoria.nfe.schema.envEventoCancSubst.TRetEnvEvento tRetEnvEvento0 = new br.com.swconsultoria.nfe.schema.envEventoCancSubst.TRetEnvEvento();
      try { 
        RetornoUtil.validaCancelamentoSubstituicao(tRetEnvEvento0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // null - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      br.com.swconsultoria.nfe.schema.envEventoCancSubst.TRetEnvEvento tRetEnvEvento0 = new br.com.swconsultoria.nfe.schema.envEventoCancSubst.TRetEnvEvento();
      tRetEnvEvento0.setCStat("128");
      RetornoUtil.validaCancelamentoSubstituicao(tRetEnvEvento0);
      assertNull(tRetEnvEvento0.getVersao());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      br.com.swconsultoria.nfe.schema.envEventoCancNFe.TRetEnvEvento tRetEnvEvento0 = new br.com.swconsultoria.nfe.schema.envEventoCancNFe.TRetEnvEvento();
      try { 
        RetornoUtil.validaCancelamento(tRetEnvEvento0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // null - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      br.com.swconsultoria.nfe.schema.envEventoCancNFe.TRetEnvEvento tRetEnvEvento0 = new br.com.swconsultoria.nfe.schema.envEventoCancNFe.TRetEnvEvento();
      tRetEnvEvento0.setCStat("128");
      RetornoUtil.validaCancelamento(tRetEnvEvento0);
      assertNull(tRetEnvEvento0.getVersao());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("204");
      try { 
        RetornoUtil.validaSincronoTrasmissaoContingencia(tRetEnviNFe0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 204 - null
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("104");
      // Undeclared exception!
      try { 
        RetornoUtil.validaSincronoTrasmissaoContingencia(tRetEnviNFe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("103");
      // Undeclared exception!
      try { 
        RetornoUtil.validaSincronoTrasmissaoContingencia(tRetEnviNFe0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.util.RetornoUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      RetornoUtil retornoUtil0 = new RetornoUtil();
  }
}
