/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 05:21:26 GMT 2024
 */

package br.com.swconsultoria.nfe.schema_4.retConsReciNFe;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema_4.retConsReciNFe.TProtNFe;
import br.com.swconsultoria.nfe.schema_4.retConsReciNFe.TRetConsReciNFe;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TRetConsReciNFe_ESTest extends TRetConsReciNFe_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setCMsg("");
      assertNull(tRetConsReciNFe0.getXMotivo());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setCStat("");
      assertNull(tRetConsReciNFe0.getVerAplic());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setXMsg("br.com.swconsultoria.nfe.schema_4.retConsReciNFe.TRetConsReciNFe");
      String string0 = tRetConsReciNFe0.getXMsg();
      assertEquals("br.com.swconsultoria.nfe.schema_4.retConsReciNFe.TRetConsReciNFe", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setXMsg("");
      String string0 = tRetConsReciNFe0.getXMsg();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setXMotivo("w]M{&4O");
      String string0 = tRetConsReciNFe0.getXMotivo();
      assertEquals("w]M{&4O", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.xMotivo = "";
      String string0 = tRetConsReciNFe0.getXMotivo();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setVersao("9H");
      String string0 = tRetConsReciNFe0.getVersao();
      assertEquals("9H", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setVersao("");
      String string0 = tRetConsReciNFe0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setVerAplic("_we-j%4");
      String string0 = tRetConsReciNFe0.getVerAplic();
      assertEquals("_we-j%4", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setVerAplic("");
      String string0 = tRetConsReciNFe0.getVerAplic();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.tpAmb = "br.com.swconsultoria.nfe.schema_4.retConsReciNFe.TRetConsReciNFe";
      String string0 = tRetConsReciNFe0.getTpAmb();
      assertEquals("br.com.swconsultoria.nfe.schema_4.retConsReciNFe.TRetConsReciNFe", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setTpAmb("");
      String string0 = tRetConsReciNFe0.getTpAmb();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      LinkedList<TProtNFe> linkedList0 = new LinkedList<TProtNFe>();
      tRetConsReciNFe0.protNFe = (List<TProtNFe>) linkedList0;
      TProtNFe tProtNFe0 = new TProtNFe();
      linkedList0.add(tProtNFe0);
      List<TProtNFe> list0 = tRetConsReciNFe0.getProtNFe();
      assertTrue(list0.contains(tProtNFe0));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.nRec = "";
      tRetConsReciNFe0.nRec = "jA79<a'pNTYWB5";
      String string0 = tRetConsReciNFe0.getNRec();
      assertEquals("jA79<a'pNTYWB5", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setNRec("");
      String string0 = tRetConsReciNFe0.getNRec();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setDhRecbto("-JOtst*-KzA");
      String string0 = tRetConsReciNFe0.getDhRecbto();
      assertEquals("-JOtst*-KzA", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setDhRecbto("");
      String string0 = tRetConsReciNFe0.getDhRecbto();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setCUF("MT");
      String string0 = tRetConsReciNFe0.getCUF();
      assertEquals("MT", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.setCUF("");
      String string0 = tRetConsReciNFe0.getCUF();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.cStat = "tN,,l\b";
      String string0 = tRetConsReciNFe0.getCStat();
      assertEquals("tN,,l\b", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.cStat = "";
      String string0 = tRetConsReciNFe0.getCStat();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.cMsg = "{J592Lj";
      String string0 = tRetConsReciNFe0.getCMsg();
      assertEquals("{J592Lj", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.cMsg = "";
      String string0 = tRetConsReciNFe0.getCMsg();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      tRetConsReciNFe0.getProtNFe();
      List<TProtNFe> list0 = tRetConsReciNFe0.getProtNFe();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      String string0 = tRetConsReciNFe0.getDhRecbto();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      String string0 = tRetConsReciNFe0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      String string0 = tRetConsReciNFe0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      String string0 = tRetConsReciNFe0.getXMsg();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      String string0 = tRetConsReciNFe0.getCUF();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      String string0 = tRetConsReciNFe0.getCStat();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      String string0 = tRetConsReciNFe0.getTpAmb();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      String string0 = tRetConsReciNFe0.getCMsg();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      String string0 = tRetConsReciNFe0.getXMotivo();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TRetConsReciNFe tRetConsReciNFe0 = new TRetConsReciNFe();
      String string0 = tRetConsReciNFe0.getNRec();
      assertNull(string0);
  }
}
