/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 10:28:01 GMT 2024
 */

package br.com.swconsultoria.nfe.schema_4.consSitNFe;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema_4.consSitNFe.SignatureType;
import br.com.swconsultoria.nfe.schema_4.consSitNFe.TRetEvento;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TRetEvento_ESTest extends TRetEvento_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setId("br.com.swconsultoria.nfe.schema_4.consSitNFe.TRetEvento");
      String string0 = tRetEvento_InfEvento0.getId();
      assertEquals("br.com.swconsultoria.nfe.schema_4.consSitNFe.TRetEvento", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNSeqEvento("");
      String string0 = tRetEvento_InfEvento0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNProt("br.com.swconsultoria.nfe.schema_4.consSitNFe.KeyInfoType");
      String string0 = tRetEvento_InfEvento0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      TRetEvento.InfEvento tRetEvento_InfEvento1 = tRetEvento0.infEvento;
      tRetEvento_InfEvento1.nProt = "9b*Q";
      String string0 = tRetEvento_InfEvento1.getNProt();
      assertEquals("9b*Q", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.cOrgao = "Ce";
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.tpAmb = "br.com.swconsultoria.nfe.schema_4.consSitNFe.TRetEvento$InfEvento";
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXMotivo("fvJfA3  1A~&>");
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setChNFe("br.com.swconsultoria.nfe.schema_4.consSitNFe.TransformsType");
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setEmailDest("");
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.nSeqEvento = "";
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.nProt = "McUcslPD8%q-)jx{";
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setEmailDest("");
      String string0 = tRetEvento_InfEvento0.getEmailDest();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCPFDest("VbA'5?0n<I.p#fa^TS");
      String string0 = tRetEvento_InfEvento0.getCPFDest();
      assertEquals("VbA'5?0n<I.p#fa^TS", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      TRetEvento.InfEvento tRetEvento_InfEvento1 = tRetEvento0.infEvento;
      tRetEvento_InfEvento1.nProt = "9b*Q";
      String string0 = tRetEvento_InfEvento0.getCNPJDest();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setEmailDest("");
      String string0 = tRetEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNProt("UEd?`A0*H");
      String string0 = tRetEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCPFDest("VbA'5?0n<I.p#fa^TS");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setId("UEd?`A0*H");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setDhRegEvento("");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCStat("");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXMotivo("fvJfA3  1A~&>");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.verAplic = "br.com.swconsultoria.nfe.schema_4.consSitNFe.TRetEvento$InfEvento";
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.nSeqEvento = "";
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.nProt = "McUcslPD8%q-)jx{";
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setTpEvento("UEd?`A0*H");
      String string0 = tRetEvento_InfEvento0.getTpEvento();
      assertEquals("UEd?`A0*H", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setChNFe("");
      String string0 = tRetEvento_InfEvento0.getChNFe();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXMotivo("fvJfA3  1A~&>");
      String string0 = tRetEvento_InfEvento0.getXMotivo();
      assertEquals("fvJfA3  1A~&>", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCStat("");
      String string0 = tRetEvento_InfEvento0.getCStat();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCOrgao("UEd?`A0*H");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.cOrgao = "Ce";
      String string0 = tRetEvento_InfEvento0.getCOrgao();
      assertEquals("Ce", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.tpEvento = "TY^X;5gu0";
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setId("Ce");
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      tRetEvento_InfEvento0.dhRegEvento = "hD1/,>x3";
      String string0 = tRetEvento0.infEvento.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXEvento("");
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCStat("br.com.swconsultoria.nfe.schema_4.consSitNFe.KeyInfoType");
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.emailDest = "Ce";
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.nSeqEvento = "";
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.nProt = "McUcslPD8%q-)jx{";
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.tpAmb = "Ce";
      String string0 = tRetEvento_InfEvento0.getTpAmb();
      assertEquals("Ce", string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.setVersao("Ce");
      assertEquals("Ce", tRetEvento0.getVersao());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      SignatureType signatureType0 = new SignatureType();
      tRetEvento0.setSignature(signatureType0);
      assertNull(tRetEvento0.getVersao());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.versao = "";
      tRetEvento0.versao = "VbA'5?0n<I.p#fa^TS";
      String string0 = tRetEvento0.getVersao();
      assertEquals("VbA'5?0n<I.p#fa^TS", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.versao = "";
      String string0 = tRetEvento0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      SignatureType signatureType0 = new SignatureType();
      tRetEvento0.signature = signatureType0;
      SignatureType signatureType1 = tRetEvento0.getSignature();
      assertNull(signatureType1.getId());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCPFDest("VbA'5?0n<I.p#fa^TS");
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCStat("http://www.w3.org/2000/09/xmldsig#rsa-sha1");
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setVerAplic("-#R[~*Ks.5f/hv#s'?6");
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNSeqEvento("br.com.swconsultoria.nfe.schema_4.consSitNFe.TRetEvento$InfEvento");
      String string0 = tRetEvento_InfEvento0.getNSeqEvento();
      assertEquals("br.com.swconsultoria.nfe.schema_4.consSitNFe.TRetEvento$InfEvento", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setChNFe("br.com.swconsultoria.nfe.schema_4.consSitNFe.TransformsType");
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setTpAmb("*6;sk&gG<RY");
      assertNull(tRetEvento_InfEvento0.getXEvento());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXMotivo("fvJfA3  1A~&>");
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCNPJDest("http://www.w3.org/2000/09/xmldsig#rsa-sha1");
      String string0 = tRetEvento_InfEvento0.getCNPJDest();
      assertEquals("http://www.w3.org/2000/09/xmldsig#rsa-sha1", string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setDhRegEvento("br.com.swconsultoria.nfe.schema_4.consSitNFe.SignedInfoType$CanonicalizationMethod");
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertEquals("br.com.swconsultoria.nfe.schema_4.consSitNFe.SignedInfoType$CanonicalizationMethod", string0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setEmailDest("");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.setInfEvento(tRetEvento_InfEvento0);
      TRetEvento.InfEvento tRetEvento_InfEvento1 = tRetEvento0.getInfEvento();
      tRetEvento_InfEvento1.tpEvento = "VbA'5?0n<I.p#fa^TS";
      String string0 = tRetEvento_InfEvento1.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = tRetEvento0.getInfEvento();
      assertNull(tRetEvento_InfEvento0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      SignatureType signatureType0 = tRetEvento0.getSignature();
      assertNull(signatureType0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      String string0 = tRetEvento0.getVersao();
      assertNull(string0);
  }
}
