/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 07:33:15 GMT 2024
 */

package br.com.swconsultoria.nfe.schema_4.inutNFe;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema_4.inutNFe.SignatureType;
import br.com.swconsultoria.nfe.schema_4.inutNFe.TInutNFe;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TInutNFe_ESTest extends TInutNFe_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setId("br.com.swconsultoria.nfe.schema_4.inutNFe.TInutNFe");
      assertNull(tInutNFe_InfInut0.getTpAmb());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.xServ = "br.com.swconsultoria.nfe.schema_4.inutNFe.SignatureType";
      String string0 = tInutNFe_InfInut0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setTpAmb("$%~EvJ7j.~.{b~/W)4E");
      String string0 = tInutNFe_InfInut0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setNNFIni("5x|<-a{T~F+");
      String string0 = tInutNFe_InfInut0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setCNPJ("br.com.swconsultoria.nfe.schema_4.inutNFe.TInutNFe");
      String string0 = tInutNFe_InfInut0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setXJust("-lFs_Y|`{5~apK%h");
      String string0 = tInutNFe_InfInut0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setSerie("oJ$ @xG");
      String string0 = tInutNFe_InfInut0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setNNFFin("1Vnsi.u(^");
      String string0 = tInutNFe_InfInut0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setCUF("br.com.swconsultoria.nfe.schema_4.inutNFe.TInutNFe$InfInut");
      String string0 = tInutNFe_InfInut0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.mod = "br.com.swconsultoria.nfe.schema_4.inutNFe.TInutNFe$InfInut";
      String string0 = tInutNFe_InfInut0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setAno(">|i}2i\n_Q");
      String string0 = tInutNFe_InfInut0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setNNFFin("br.com.swconsultoria.nfe.schema_4.inutNFe.TInutNFe");
      String string0 = tInutNFe_InfInut0.getNNFFin();
      assertEquals("br.com.swconsultoria.nfe.schema_4.inutNFe.TInutNFe", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.nnfIni = "";
      String string0 = tInutNFe_InfInut0.getNNFIni();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setSerie("Gn,N*8T6z");
      String string0 = tInutNFe_InfInut0.getSerie();
      assertEquals("Gn,N*8T6z", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setMod("cUYyQ~98;'*UM`a3");
      String string0 = tInutNFe_InfInut0.getSerie();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setMod("TM;:>X");
      String string0 = tInutNFe_InfInut0.getMod();
      assertEquals("TM;:>X", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      TInutNFe tInutNFe0 = new TInutNFe();
      tInutNFe0.setInfInut(tInutNFe_InfInut0);
      TInutNFe.InfInut tInutNFe_InfInut1 = tInutNFe0.infInut;
      tInutNFe_InfInut1.ano = "edTtZwtpPa&F>_7";
      tInutNFe_InfInut0.setAno((String) null);
      assertNull(tInutNFe_InfInut0.getTpAmb());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.mod = "yK<OtRNNdQO|pOm ";
      String string0 = tInutNFe_InfInut0.getAno();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.cuf = "";
      String string0 = tInutNFe_InfInut0.getCUF();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setXServ("http://www.w3.org/2000/09/xmldsig#rsa-sha1");
      assertNull(tInutNFe_InfInut0.getCNPJ());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.xServ = "";
      String string0 = tInutNFe_InfInut0.getXServ();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TInutNFe tInutNFe0 = new TInutNFe();
      SignatureType signatureType0 = new SignatureType();
      tInutNFe0.setSignature(signatureType0);
      assertNull(tInutNFe0.getVersao());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TInutNFe tInutNFe0 = new TInutNFe();
      tInutNFe0.setVersao("~[1B&\"3~BN },.-");
      String string0 = tInutNFe0.getVersao();
      assertEquals("~[1B&\"3~BN },.-", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TInutNFe tInutNFe0 = new TInutNFe();
      SignatureType signatureType0 = new SignatureType();
      tInutNFe0.signature = signatureType0;
      SignatureType signatureType1 = tInutNFe0.getSignature();
      assertSame(signatureType1, signatureType0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TInutNFe tInutNFe0 = new TInutNFe();
      String string0 = tInutNFe0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TInutNFe tInutNFe0 = new TInutNFe();
      SignatureType signatureType0 = tInutNFe0.getSignature();
      assertNull(signatureType0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      TInutNFe tInutNFe0 = new TInutNFe();
      tInutNFe0.setInfInut(tInutNFe_InfInut0);
      TInutNFe.InfInut tInutNFe_InfInut1 = tInutNFe0.getInfInut();
      assertNull(tInutNFe_InfInut1.getSerie());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TInutNFe tInutNFe0 = new TInutNFe();
      tInutNFe0.setVersao("");
      String string0 = tInutNFe0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TInutNFe tInutNFe0 = new TInutNFe();
      TInutNFe.InfInut tInutNFe_InfInut0 = tInutNFe0.getInfInut();
      assertNull(tInutNFe_InfInut0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setXJust("");
      String string0 = tInutNFe_InfInut0.getXJust();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      String string0 = tInutNFe_InfInut0.getCNPJ();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      String string0 = tInutNFe_InfInut0.getTpAmb();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setTpAmb("$%~EvJ7j.~.{b~/W)4E");
      String string0 = tInutNFe_InfInut0.getTpAmb();
      assertEquals("$%~EvJ7j.~.{b~/W)4E", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TInutNFe.InfInut tInutNFe_InfInut0 = new TInutNFe.InfInut();
      tInutNFe_InfInut0.setCNPJ("");
      String string0 = tInutNFe_InfInut0.getCNPJ();
      assertEquals("", string0);
  }
}
