/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 05:49:35 GMT 2024
 */

package br.com.swconsultoria.nfe.schema_4.enviNFe;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TEndereco;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TUf;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TEndereco_ESTest extends TEndereco_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setXCpl("o]");
      assertNull(tEndereco0.getCEP());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setXLgr("");
      assertNull(tEndereco0.getFone());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.xPais = "Lv*";
      String string0 = tEndereco0.getXPais();
      assertEquals("Lv*", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.xPais = "";
      String string0 = tEndereco0.getXPais();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setXMun("H<;!{bF-fR9hx");
      String string0 = tEndereco0.getXMun();
      assertEquals("H<;!{bF-fR9hx", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setXMun("");
      String string0 = tEndereco0.getXMun();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.xLgr = "H!L,)+u[ZSfSQ";
      String string0 = tEndereco0.getXLgr();
      assertEquals("H!L,)+u[ZSfSQ", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.xLgr = "";
      String string0 = tEndereco0.getXLgr();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.xCpl = "TO";
      String string0 = tEndereco0.getXCpl();
      assertEquals("TO", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.xCpl = "";
      String string0 = tEndereco0.getXCpl();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setXBairro("br.com.swconsultoria.nfe.schema_4.enviNFe.TEndereco");
      String string0 = tEndereco0.getXBairro();
      assertEquals("br.com.swconsultoria.nfe.schema_4.enviNFe.TEndereco", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setXBairro("");
      String string0 = tEndereco0.getXBairro();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      TUf tUf0 = TUf.TO;
      tEndereco0.setUF(tUf0);
      TUf tUf1 = tEndereco0.getUF();
      assertEquals(TUf.TO, tUf1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.nro = "k";
      String string0 = tEndereco0.getNro();
      assertEquals("k", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setNro("");
      String string0 = tEndereco0.getNro();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setFone("Vn{,>.");
      String string0 = tEndereco0.getFone();
      assertEquals("Vn{,>.", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.fone = "";
      String string0 = tEndereco0.getFone();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setCPais("Jf/I[Dm$2_G/l}Q_x");
      String string0 = tEndereco0.getCPais();
      assertEquals("Jf/I[Dm$2_G/l}Q_x", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.cMun = "9SZ2t[7y75Njx";
      String string0 = tEndereco0.getCMun();
      assertEquals("9SZ2t[7y75Njx", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setCMun("");
      String string0 = tEndereco0.getCMun();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setCEP("H!L,)+u[ZSfSQ");
      String string0 = tEndereco0.getCEP();
      assertEquals("H!L,)+u[ZSfSQ", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setCEP("");
      String string0 = tEndereco0.getCEP();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setCPais("");
      String string0 = tEndereco0.getCPais();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      String string0 = tEndereco0.getCEP();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.getUF();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      String string0 = tEndereco0.getXCpl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      String string0 = tEndereco0.getCPais();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      String string0 = tEndereco0.getNro();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      String string0 = tEndereco0.getCMun();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      String string0 = tEndereco0.getXLgr();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      String string0 = tEndereco0.getXBairro();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      String string0 = tEndereco0.getXPais();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      String string0 = tEndereco0.getFone();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      tEndereco0.setXPais("");
      assertNull(tEndereco0.getXBairro());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TEndereco tEndereco0 = new TEndereco();
      String string0 = tEndereco0.getXMun();
      assertNull(string0);
  }
}
