/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 02:40:40 GMT 2024
 */

package br.com.swconsultoria.nfe.schema_4.enviNFe;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TInfRespTec;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TUfEmi;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TVeiculo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TNFe_ESTest extends TNFe_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.picmsst = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.pCredSN = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN((String) null);
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS15 tNFe_InfNFe_Det_Imposto_ICMS_ICMS15_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS15();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS15_0.setAdRemICMSReten("'_~'&iXIYF8s^~>q");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS15_0.setQBCMono("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS15_0.getQBCMonoReten();
      TNFe.InfNFe.InfAdic.ProcRef tNFe_InfNFe_InfAdic_ProcRef0 = new TNFe.InfNFe.InfAdic.ProcRef();
      tNFe_InfNFe_InfAdic_ProcRef0.setNProc("'_~'&iXIYF8s^~>q");
      tNFe_InfNFe_InfAdic_ProcRef0.setTpAto("");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      TNFe.InfNFe.Det.Imposto.PIS.PISAliq tNFe_InfNFe_Det_Imposto_PIS_PISAliq0 = tNFe_InfNFe_Det_Imposto_PIS0.pisAliq;
      tNFe_InfNFe_Det_Imposto_PIS0.setPISAliq((TNFe.InfNFe.Det.Imposto.PIS.PISAliq) null);
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSST tNFe_InfNFe_Det_Imposto_ICMS_ICMSST0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSST();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSST0.setVICMSSTRet((String) null);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.PISST tNFe_InfNFe_Det_Imposto_PISST0 = new TNFe.InfNFe.Det.Imposto.PISST();
      tNFe_InfNFe_Det_Imposto_PISST0.setPPIS("");
      tNFe_InfNFe_Det_Imposto_PISST0.setVPIS((String) null);
      tNFe_InfNFe_Det_Imposto_PISST0.getVAliqProd();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMSUFDest tNFe_InfNFe_Det_Imposto_ICMSUFDest0 = new TNFe.InfNFe.Det.Imposto.ICMSUFDest();
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.setPFCPUFDest("O0#sp@vWNC=M%al");
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.vicmsufDest = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Prod$InfProdEmb";
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.setVICMSUFDest("");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMSUFDest tNFe_InfNFe_Det_Imposto_ICMSUFDest0 = new TNFe.InfNFe.Det.Imposto.ICMSUFDest();
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.setPICMSUFDest("gu1m2");
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.setVBCFCPUFDest("EX");
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.picmsufDest = null;
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.setPICMSUFDest("br.com.swconsultoria.nfe.schema_4.enviNFe.TVeiculo");
      TNFe.InfNFe.Det.Imposto.COFINSST tNFe_InfNFe_Det_Imposto_COFINSST0 = new TNFe.InfNFe.Det.Imposto.COFINSST();
      tNFe_InfNFe_Det_Imposto_COFINSST0.getVCOFINS();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TNFe.InfNFe.Ide.NFref tNFe_InfNFe_Ide_NFref0 = new TNFe.InfNFe.Ide.NFref();
      tNFe_InfNFe_Ide_NFref0.getRefNFP();
      tNFe_InfNFe_Ide_NFref0.refNFP = null;
      tNFe_InfNFe_Ide_NFref0.setRefNFeSig((String) null);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TNFe.InfNFe.Total.ICMSTot tNFe_InfNFe_Total_ICMSTot0 = new TNFe.InfNFe.Total.ICMSTot();
      tNFe_InfNFe_Total_ICMSTot0.setVFCPST("GO");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TNFe.InfNFe.Total.ICMSTot tNFe_InfNFe_Total_ICMSTot0 = new TNFe.InfNFe.Total.ICMSTot();
      tNFe_InfNFe_Total_ICMSTot0.setQBCMonoReten("o?_T!r$`YmbpEg");
      tNFe_InfNFe_Total_ICMSTot0.vii = "";
      tNFe_InfNFe_Total_ICMSTot0.getVICMSUFRemet();
      TNFe.InfNFe.Det.ObsItem.ObsFisco tNFe_InfNFe_Det_ObsItem_ObsFisco0 = new TNFe.InfNFe.Det.ObsItem.ObsFisco();
      tNFe_InfNFe_Det_ObsItem_ObsFisco0.setXTexto((String) null);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TNFe.InfNFe.Transp.Vol tNFe_InfNFe_Transp_Vol0 = new TNFe.InfNFe.Transp.Vol();
      tNFe_InfNFe_Transp_Vol0.qVol = "J#Xl1(=p3[%D[NS";
      tNFe_InfNFe_Transp_Vol0.getLacres();
      TNFe.InfNFe.Det.Prod.Arma tNFe_InfNFe_Det_Prod_Arma0 = new TNFe.InfNFe.Det.Prod.Arma();
      tNFe_InfNFe_Det_Prod_Arma0.tpArma = null;
      tNFe_InfNFe_Det_Prod_Arma0.setNSerie("");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TNFe.InfNFe.Transp.Vol.Lacres tNFe_InfNFe_Transp_Vol_Lacres0 = new TNFe.InfNFe.Transp.Vol.Lacres();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS tNFe_InfNFe_Det_Imposto_ICMS0 = new TNFe.InfNFe.Det.Imposto.ICMS();
      tNFe_InfNFe_Det_Imposto_ICMS0.getICMSSN102();
      TNFe.InfNFe.Ide tNFe_InfNFe_Ide0 = new TNFe.InfNFe.Ide();
      tNFe_InfNFe_Ide0.getIndFinal();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.COFINS.COFINSOutr tNFe_InfNFe_Det_Imposto_COFINS_COFINSOutr0 = new TNFe.InfNFe.Det.Imposto.COFINS.COFINSOutr();
      tNFe_InfNFe_Det_Imposto_COFINS_COFINSOutr0.setQBCProd(":+~%l)m{V=o4 t");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS60 tNFe_InfNFe_Det_Imposto_ICMS_ICMS60_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS60();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS60_0.getPICMSEfet();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0 = new TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde();
      tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0.setVAliqProd("");
      TNFe.InfNFe.Det.Imposto.ICMS tNFe_InfNFe_Det_Imposto_ICMS0 = new TNFe.InfNFe.Det.Imposto.ICMS();
      tNFe_InfNFe_Det_Imposto_ICMS0.getICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS0.setICMSSN101((TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101) null);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TNFe.InfNFe.Det tNFe_InfNFe_Det0 = new TNFe.InfNFe.Det();
      tNFe_InfNFe_Det0.getProd();
      tNFe_InfNFe_Det0.setProd((TNFe.InfNFe.Det.Prod) null);
      tNFe_InfNFe_Det0.getInfAdProd();
      TNFe.InfNFe.Total.RetTrib tNFe_InfNFe_Total_RetTrib0 = new TNFe.InfNFe.Total.RetTrib();
      tNFe_InfNFe_Total_RetTrib0.getVBCRetPrev();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TNFe.InfNFe.Det tNFe_InfNFe_Det0 = new TNFe.InfNFe.Det();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det0.setProd(tNFe_InfNFe_Det_Prod0);
      TNFe.InfNFe.Ide tNFe_InfNFe_Ide0 = new TNFe.InfNFe.Ide();
      tNFe_InfNFe_Ide0.setIndPres("");
      tNFe_InfNFe_Ide0.setCNF("ENUM$VALUES");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS90 tNFe_InfNFe_Det_Imposto_ICMS_ICMS90_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS90();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS90_0.getMotDesICMSST();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TNFe.InfNFeSupl tNFe_InfNFeSupl0 = new TNFe.InfNFeSupl();
      tNFe_InfNFeSupl0.setQrCode("4}3]s]xi0Dh262{oO");
      tNFe_InfNFeSupl0.urlChave = "Bb$(P9ri8Z>K";
      tNFe_InfNFeSupl0.getUrlChave();
      TNFe.InfNFe.Det.ObsItem.ObsCont tNFe_InfNFe_Det_ObsItem_ObsCont0 = new TNFe.InfNFe.Det.ObsItem.ObsCont();
      tNFe_InfNFe_Det_ObsItem_ObsCont0.xTexto = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMSUFDest";
      tNFe_InfNFe_Det_ObsItem_ObsCont0.setXCampo("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$ImpostoDevol");
      tNFe_InfNFe_Det_ObsItem_ObsCont0.setXCampo("");
      TNFe.InfNFe.Ide.NFref.RefNF tNFe_InfNFe_Ide_NFref_RefNF0 = new TNFe.InfNFe.Ide.NFref.RefNF();
      TNFe.InfNFe.Ide tNFe_InfNFe_Ide0 = new TNFe.InfNFe.Ide();
      tNFe_InfNFe_Ide0.setProcEmi("4}3]s]xi0Dh262{oO");
      tNFe_InfNFe_Ide0.getSerie();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS15 tNFe_InfNFe_Det_Imposto_ICMS_ICMS15_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS15();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS15_0.adRemICMS = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS15_0.setAdRemICMS("-wj4jbjN");
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ISSQN tNFe_InfNFe_Det_Imposto_ISSQN0 = new TNFe.InfNFe.Det.Imposto.ISSQN();
      tNFe_InfNFe_Det_Imposto_ISSQN0.vDescIncond = "br.com.swconsultoria.nfe.schema_4.enviNFe.SignedInfoType";
      tNFe_InfNFe_Det_Imposto_ISSQN0.cMunFG = "";
      tNFe_InfNFe_Det_Imposto_ISSQN0.setVDescIncond("");
      tNFe_InfNFe_Det_Imposto_ISSQN0.setCListServ((String) null);
      tNFe_InfNFe_Det_Imposto_ISSQN0.vDescIncond = "y{Y_c^[WmujKHS3*a;a";
      tNFe_InfNFe_Det_Imposto_ISSQN0.vAliq = "br.com.swconsultoria.nfe.schema_4.enviNFe.TInfRespTec";
      tNFe_InfNFe_Det_Imposto_ISSQN0.vAliq = "br.com.swconsultoria.nfe.schema_4.enviNFe.TInfRespTec";
      tNFe_InfNFe_Det_Imposto_ISSQN0.getIndISS();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TNFe.InfNFe tNFe_InfNFe0 = new TNFe.InfNFe();
      tNFe_InfNFe0.infAdic = null;
      TNFe.InfNFe.Ide tNFe_InfNFe_Ide0 = new TNFe.InfNFe.Ide();
      tNFe_InfNFe0.ide = tNFe_InfNFe_Ide0;
      tNFe_InfNFe0.getTotal();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSPart tNFe_InfNFe_Det_Imposto_ICMS_ICMSPart0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSPart();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSPart0.setPICMSST("");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS90 tNFe_InfNFe_Det_Imposto_ICMS_ICMS90_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS90();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS90_0.setPFCP("ylTHxLgnjm,:gj8!");
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TNFe.InfNFe.Pag.DetPag tNFe_InfNFe_Pag_DetPag0 = new TNFe.InfNFe.Pag.DetPag();
      tNFe_InfNFe_Pag_DetPag0.setIndPag("");
      tNFe_InfNFe_Pag_DetPag0.xPag = "";
      tNFe_InfNFe_Pag_DetPag0.setXPag("");
      tNFe_InfNFe_Pag_DetPag0.indPag = "";
      tNFe_InfNFe_Pag_DetPag0.getVPag();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TNFe.InfNFe.Ide.NFref tNFe_InfNFe_Ide_NFref0 = new TNFe.InfNFe.Ide.NFref();
      TNFe.InfNFe.Ide.NFref.RefNF tNFe_InfNFe_Ide_NFref_RefNF0 = tNFe_InfNFe_Ide_NFref0.refNF;
      tNFe_InfNFe_Ide_NFref0.setRefNF((TNFe.InfNFe.Ide.NFref.RefNF) null);
      tNFe_InfNFe_Ide_NFref0.getRefNF();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS30 tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS30();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0.setVBCST("7\u0007");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0.orig = "7\u0007";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0.setPRedBCST("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0.getModBCST();
      TNFe.InfNFe.Dest tNFe_InfNFe_Dest0 = new TNFe.InfNFe.Dest();
      tNFe_InfNFe_Dest0.cnpj = "";
      tNFe_InfNFe_Dest0.setIM("");
      TNFe.InfNFe.Cobr.Dup tNFe_InfNFe_Cobr_Dup0 = new TNFe.InfNFe.Cobr.Dup();
      tNFe_InfNFe_Cobr_Dup0.getNDup();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS40 tNFe_InfNFe_Det_Imposto_ICMS_ICMS40_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS40();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS40_0.setVICMSDeson("");
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TNFe.InfNFe.Cobr.Dup tNFe_InfNFe_Cobr_Dup0 = new TNFe.InfNFe.Cobr.Dup();
      tNFe_InfNFe_Cobr_Dup0.setNDup("fOGv#F`lo-[:r");
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS60 tNFe_InfNFe_Det_Imposto_ICMS_ICMS60_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS60();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS60_0.setVBCFCPSTRet((String) null);
      TNFe.InfNFe.InfAdic.ProcRef tNFe_InfNFe_InfAdic_ProcRef0 = new TNFe.InfNFe.InfAdic.ProcRef();
      tNFe_InfNFe_InfAdic_ProcRef0.getNProc();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS02 tNFe_InfNFe_Det_Imposto_ICMS_ICMS02_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS02();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS02_0.cst = "ae(";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS02_0.getVICMSMono();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS51 tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS51();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0.setPICMS("ae(");
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS tNFe_InfNFe_Det_Imposto_ICMS0 = new TNFe.InfNFe.Det.Imposto.ICMS();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSST tNFe_InfNFe_Det_Imposto_ICMS_ICMSST0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSST();
      tNFe_InfNFe_Det_Imposto_ICMS0.setICMSST(tNFe_InfNFe_Det_Imposto_ICMS_ICMSST0);
      tNFe_InfNFe_Det_Imposto_ICMS0.setICMS02((TNFe.InfNFe.Det.Imposto.ICMS.ICMS02) null);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TNFe.InfNFe.InfAdic.ProcRef tNFe_InfNFe_InfAdic_ProcRef0 = new TNFe.InfNFe.InfAdic.ProcRef();
      tNFe_InfNFe_InfAdic_ProcRef0.tpAto = "ay_#};-";
      tNFe_InfNFe_InfAdic_ProcRef0.setNProc((String) null);
      tNFe_InfNFe_InfAdic_ProcRef0.setIndProc("DmiWABSVE$J{");
      tNFe_InfNFe_InfAdic_ProcRef0.setNProc("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfIntermed");
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TNFe.InfNFe.Total.ICMSTot tNFe_InfNFe_Total_ICMSTot0 = new TNFe.InfNFe.Total.ICMSTot();
      tNFe_InfNFe_Total_ICMSTot0.setQBCMono("5)`-W~5fP");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS90 tNFe_InfNFe_Det_Imposto_ICMS_ICMS90_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS90();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS90_0.setCST("5)`-W~5fP");
      TNFe.InfNFe.Det.Prod.DI tNFe_InfNFe_Det_Prod_DI0 = new TNFe.InfNFe.Det.Prod.DI();
      TUfEmi tUfEmi0 = TUfEmi.TO;
      tNFe_InfNFe_Det_Prod_DI0.setUFDesemb(tUfEmi0);
      tNFe_InfNFe_Det_Prod_DI0.getDDesemb();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS51 tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS51();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0.setVICMSDif((String) null);
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0.getModBC();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS00 tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS00();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0.setVFCP("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0.setVICMS("@:+fNXvp6");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0.setModBC("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0.getCST();
      TNFe tNFe0 = new TNFe();
      tNFe0.getSignature();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TNFe.InfNFe.Total.ICMSTot tNFe_InfNFe_Total_ICMSTot0 = new TNFe.InfNFe.Total.ICMSTot();
      tNFe_InfNFe_Total_ICMSTot0.setVTotTrib(";xF7p.S(h:^");
      tNFe_InfNFe_Total_ICMSTot0.setVFCPST("GO");
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.PISST tNFe_InfNFe_Det_Imposto_PISST0 = new TNFe.InfNFe.Det.Imposto.PISST();
      tNFe_InfNFe_Det_Imposto_PISST0.setQBCProd("^jv-}~=</@O[yd");
      tNFe_InfNFe_Det_Imposto_PISST0.setPPIS("");
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS00 tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS00();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0.vicms = "@:+fNXvp6";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0.setVFCP("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0.setVICMS("@:+fNXvp6");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0.setModBC("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS00_0.getCST();
      TNFe tNFe0 = new TNFe();
      tNFe0.getInfNFe();
      tNFe0.setInfNFe((TNFe.InfNFe) null);
      tNFe0.getSignature();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSPart tNFe_InfNFe_Det_Imposto_ICMS_ICMSPart0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSPart();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSPart0.getPMVAST();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      TNFe.InfNFe.Det.Prod.VeicProd tNFe_InfNFe_Det_Prod_VeicProd0 = new TNFe.InfNFe.Det.Prod.VeicProd();
      tNFe_InfNFe_Det_Prod0.veicProd = tNFe_InfNFe_Det_Prod_VeicProd0;
      tNFe_InfNFe_Det_Prod0.nItemPed = "h@P";
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      TNFe.InfNFe.Total.ICMSTot tNFe_InfNFe_Total_ICMSTot0 = new TNFe.InfNFe.Total.ICMSTot();
      TNFe.InfNFe.Det.Prod.DI tNFe_InfNFe_Det_Prod_DI0 = new TNFe.InfNFe.Det.Prod.DI();
      tNFe_InfNFe_Det_Prod_DI0.getCExportador();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.getPICMS();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS60 tNFe_InfNFe_Det_Imposto_ICMS_ICMS60_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS60();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS60_0.getCST();
      TNFe.InfNFe.Det.Imposto.ICMS tNFe_InfNFe_Det_Imposto_ICMS0 = new TNFe.InfNFe.Det.Imposto.ICMS();
      TNFe.InfNFe.Det.Imposto.ICMS tNFe_InfNFe_Det_Imposto_ICMS1 = new TNFe.InfNFe.Det.Imposto.ICMS();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN201_0 = tNFe_InfNFe_Det_Imposto_ICMS1.icmssn201;
      tNFe_InfNFe_Det_Imposto_ICMS0.setICMSSN201((TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201) null);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      TNFe.InfNFe.Avulsa tNFe_InfNFe_Avulsa0 = new TNFe.InfNFe.Avulsa();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPICMSST("");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.PIS.PISOutr tNFe_InfNFe_Det_Imposto_PIS_PISOutr0 = new TNFe.InfNFe.Det.Imposto.PIS.PISOutr();
      tNFe_InfNFe_Det_Imposto_PIS_PISOutr0.vAliqProd = "";
      tNFe_InfNFe_Det_Imposto_PIS_PISOutr0.setQBCProd(":IFV]S");
      tNFe_InfNFe_Det_Imposto_PIS_PISOutr0.getVPIS();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS30 tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS30();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0.setPMVAST(":IFV]S");
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setQCom("BA");
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setModFrete("");
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.picmsst = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS51 tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS51();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0.setModBC("wCh7z):15Fv/CRDT}>=");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0.setModBC((String) null);
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0.setVICMSDif((String) null);
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0.getModBC();
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      TNFe.InfNFe.Det.Imposto.ISSQN tNFe_InfNFe_Det_Imposto_ISSQN0 = new TNFe.InfNFe.Det.Imposto.ISSQN();
      tNFe_InfNFe_Det_Imposto_ISSQN0.setIndIncentivo("lWV3,V");
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      TNFe.InfNFe.Total.ICMSTot tNFe_InfNFe_Total_ICMSTot0 = new TNFe.InfNFe.Total.ICMSTot();
      tNFe_InfNFe_Total_ICMSTot0.setQBCMono("5)`-W~5fP");
      TNFe.InfNFe.Det tNFe_InfNFe_Det0 = new TNFe.InfNFe.Det();
      tNFe_InfNFe_Det0.getNItem();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS90 tNFe_InfNFe_Det_Imposto_ICMS_ICMS90_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS90();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS90_0.getPRedBCST();
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      TVeiculo tVeiculo0 = tNFe_InfNFe_Transp0.veicTransp;
      tNFe_InfNFe_Transp0.veicTransp = null;
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.Det.Imposto.ICMSUFDest tNFe_InfNFe_Det_Imposto_ICMSUFDest0 = new TNFe.InfNFe.Det.Imposto.ICMSUFDest();
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.getPICMSInterPart();
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      TNFe.InfNFe.Det tNFe_InfNFe_Det0 = new TNFe.InfNFe.Det();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getArma();
      tNFe_InfNFe_Det0.setProd(tNFe_InfNFe_Det_Prod0);
      TNFe.InfNFe.Ide tNFe_InfNFe_Ide0 = new TNFe.InfNFe.Ide();
      tNFe_InfNFe_Ide0.setIndPres("");
      tNFe_InfNFe_Ide0.setCNF("ENUM$VALUES");
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPICMSST("");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setRetTransp((TNFe.InfNFe.Transp.RetTransp) null);
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.Det.Imposto.ICMS tNFe_InfNFe_Det_Imposto_ICMS0 = new TNFe.InfNFe.Det.Imposto.ICMS();
      tNFe_InfNFe_Det_Imposto_ICMS0.getICMS90();
      tNFe_InfNFe_Det_Imposto_ICMS0.setICMS90((TNFe.InfNFe.Det.Imposto.ICMS.ICMS90) null);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPICMSST("");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setRetTransp((TNFe.InfNFe.Transp.RetTransp) null);
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      tNFe_InfNFe_Transp0.getTransporta();
      TNFe.InfNFe.Cobr tNFe_InfNFe_Cobr0 = new TNFe.InfNFe.Cobr();
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setNRECOPI("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPICMSST("");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setRetTransp((TNFe.InfNFe.Transp.RetTransp) null);
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.Det.Imposto.ICMS tNFe_InfNFe_Det_Imposto_ICMS0 = new TNFe.InfNFe.Det.Imposto.ICMS();
      tNFe_InfNFe_Det_Imposto_ICMS0.setICMSSN900(tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0);
      tNFe_InfNFe_Det_Imposto_ICMS0.getICMSPart();
      tNFe_InfNFe_Det_Imposto_ICMS0.setICMSPart((TNFe.InfNFe.Det.Imposto.ICMS.ICMSPart) null);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPRedBCST("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      TNFe.InfNFe.Total.ICMSTot tNFe_InfNFe_Total_ICMSTot0 = new TNFe.InfNFe.Total.ICMSTot();
      tNFe_InfNFe_Total_ICMSTot0.setVII("");
      tNFe_InfNFe_Total_ICMSTot0.setQBCMono("5)`-W~5fP");
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      TNFe.InfNFe.Det.Prod.VeicProd tNFe_InfNFe_Det_Prod_VeicProd0 = new TNFe.InfNFe.Det.Prod.VeicProd();
      tNFe_InfNFe_Det_Prod_VeicProd0.getAnoFab();
      TNFe.InfNFe.Transp.Vol tNFe_InfNFe_Transp_Vol0 = new TNFe.InfNFe.Transp.Vol();
      tNFe_InfNFe_Transp_Vol0.nVol = "MvXld6H|SiG3%@U;";
      tNFe_InfNFe_Transp_Vol0.getQVol();
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("br.com.swconsultoria.nfe.schema_4.enviNFe.TUfEmi");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.Det.Prod.InfProdNFF tNFe_InfNFe_Det_Prod_InfProdNFF0 = new TNFe.InfNFe.Det.Prod.InfProdNFF();
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      TNFe.InfNFe.Det tNFe_InfNFe_Det0 = new TNFe.InfNFe.Det();
      TNFe.InfNFe.Det.ObsItem tNFe_InfNFe_Det_ObsItem0 = new TNFe.InfNFe.Det.ObsItem();
      tNFe_InfNFe_Det0.setObsItem(tNFe_InfNFe_Det_ObsItem0);
      TNFe.InfNFe.Det.Imposto.COFINSST tNFe_InfNFe_Det_Imposto_COFINSST0 = new TNFe.InfNFe.Det.Imposto.COFINSST();
      tNFe_InfNFe_Det_Imposto_COFINSST0.setIndSomaCOFINSST("\"Cl?");
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setVCredICMSSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      tNFe_InfNFe_Det_Prod0.getNRECOPI();
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.InfAdic.ObsCont tNFe_InfNFe_InfAdic_ObsCont0 = new TNFe.InfNFe.InfAdic.ObsCont();
      tNFe_InfNFe_InfAdic_ObsCont0.setXCampo("");
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0 = new TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde();
      tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0.setVCOFINS("El7]WFp&Px$gDCh]");
      tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0.setVAliqProd("&");
      TNFe.InfNFe.Det.Imposto.ICMS tNFe_InfNFe_Det_Imposto_ICMS0 = new TNFe.InfNFe.Det.Imposto.ICMS();
      tNFe_InfNFe_Det_Imposto_ICMS0.getICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS0.setICMSSN101((TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101) null);
      TNFe.InfNFe.Det.Imposto.COFINSST tNFe_InfNFe_Det_Imposto_COFINSST0 = new TNFe.InfNFe.Det.Imposto.COFINSST();
      tNFe_InfNFe_Det_Imposto_COFINSST0.getIndSomaCOFINSST();
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      TNFe.InfNFe.Det.Prod.VeicProd tNFe_InfNFe_Det_Prod_VeicProd0 = tNFe_InfNFe_Det_Prod0.veicProd;
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setCSOSN("VNE)L");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      TNFe.InfNFe.Det.Prod.DetExport tNFe_InfNFe_Det_Prod_DetExport0 = new TNFe.InfNFe.Det.Prod.DetExport();
      TNFe.InfNFe.Det.Prod.DetExport.ExportInd tNFe_InfNFe_Det_Prod_DetExport_ExportInd0 = new TNFe.InfNFe.Det.Prod.DetExport.ExportInd();
      tNFe_InfNFe_Det_Prod_DetExport_ExportInd0.setNRE("");
      tNFe_InfNFe_Det_Prod_DetExport0.setExportInd(tNFe_InfNFe_Det_Prod_DetExport_ExportInd0);
      TNFe.InfNFe.Det.Prod.DetExport.ExportInd tNFe_InfNFe_Det_Prod_DetExport_ExportInd1 = tNFe_InfNFe_Det_Prod_DetExport0.exportInd;
      tNFe_InfNFe_Det_Prod_DetExport0.setExportInd(tNFe_InfNFe_Det_Prod_DetExport_ExportInd1);
      TNFe tNFe0 = new TNFe();
      TNFe.InfNFe tNFe_InfNFe0 = new TNFe.InfNFe();
      tNFe0.setInfNFe(tNFe_InfNFe0);
      TNFe.InfNFe tNFe_InfNFe1 = tNFe0.getInfNFe();
      tNFe_InfNFe1.getInfRespTec();
      tNFe_InfNFe1.setInfRespTec((TInfRespTec) null);
      tNFe0.getInfNFe();
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getRastro();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      TVeiculo tVeiculo0 = tNFe_InfNFe_Transp0.veicTransp;
      tNFe_InfNFe_Transp0.veicTransp = null;
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.pRedBC = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.Det.Imposto.ICMSUFDest tNFe_InfNFe_Det_Imposto_ICMSUFDest0 = new TNFe.InfNFe.Det.Imposto.ICMSUFDest();
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.getPICMSInterPart();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN201_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN201_0.getPCredSN();
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0 = new TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde();
      tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0.setQBCProd("");
      tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0.setVAliqProd("");
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS51 tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS51();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0.setVICMSDif((String) null);
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0.getCST();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS51_0.setVFCPDif((String) null);
      TNFe.InfNFe.Det.Imposto.PIS.PISAliq tNFe_InfNFe_Det_Imposto_PIS_PISAliq0 = new TNFe.InfNFe.Det.Imposto.PIS.PISAliq();
      tNFe_InfNFe_Det_Imposto_PIS_PISAliq0.setVBC("Iaw9|tMMQX;#[MX");
      TNFe.InfNFe.Det.Prod.Rastro tNFe_InfNFe_Det_Prod_Rastro0 = new TNFe.InfNFe.Det.Prod.Rastro();
      tNFe_InfNFe_Det_Prod_Rastro0.getQLote();
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setVBCST((String) null);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPMVAST("");
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPICMSST("");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setRetTransp((TNFe.InfNFe.Transp.RetTransp) null);
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      tNFe_InfNFe_Transp0.getTransporta();
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPRedBCST("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS1 = new TNFe.InfNFe.Det.Imposto.PIS();
      TNFe.InfNFe.Det.Imposto.PIS.PISNT tNFe_InfNFe_Det_Imposto_PIS_PISNT0 = tNFe_InfNFe_Det_Imposto_PIS1.pisnt;
      tNFe_InfNFe_Det_Imposto_PIS0.setPISNT((TNFe.InfNFe.Det.Imposto.PIS.PISNT) null);
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setNFCI(";n|V4jMvKo<<");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.Det.Imposto.ICMS tNFe_InfNFe_Det_Imposto_ICMS0 = new TNFe.InfNFe.Det.Imposto.ICMS();
      tNFe_InfNFe_Det_Imposto_ICMS0.getICMS30();
      tNFe_InfNFe_Det_Imposto_ICMS0.setICMS30((TNFe.InfNFe.Det.Imposto.ICMS.ICMS30) null);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      TNFe.InfNFe.Det.Imposto.PIS.PISQtde tNFe_InfNFe_Det_Imposto_PIS_PISQtde0 = tNFe_InfNFe_Det_Imposto_PIS0.pisQtde;
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      TVeiculo tVeiculo0 = tNFe_InfNFe_Transp0.veicTransp;
      tNFe_InfNFe_Transp0.veicTransp = null;
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPRedBC("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.Det.Imposto.ICMSUFDest tNFe_InfNFe_Det_Imposto_ICMSUFDest0 = new TNFe.InfNFe.Det.Imposto.ICMSUFDest();
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.getPICMSInterPart();
      TNFe.InfNFe.Total.ISSQNtot tNFe_InfNFe_Total_ISSQNtot0 = new TNFe.InfNFe.Total.ISSQNtot();
      tNFe_InfNFe_Total_ISSQNtot0.setVCOFINS((String) null);
      tNFe_InfNFe_Det_Prod0.setVeicProd((TNFe.InfNFe.Det.Prod.VeicProd) null);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS tNFe_InfNFe_Det_Imposto_ICMS0 = new TNFe.InfNFe.Det.Imposto.ICMS();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS70 tNFe_InfNFe_Det_Imposto_ICMS_ICMS70_0 = tNFe_InfNFe_Det_Imposto_ICMS0.icms70;
      tNFe_InfNFe_Det_Imposto_ICMS0.icms70 = null;
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS90 tNFe_InfNFe_Det_Imposto_ICMS_ICMS90_0 = tNFe_InfNFe_Det_Imposto_ICMS0.icms90;
      tNFe_InfNFe_Det_Imposto_ICMS0.setICMS90((TNFe.InfNFe.Det.Imposto.ICMS.ICMS90) null);
      tNFe_InfNFe_Det_Imposto_ICMS0.getICMS53();
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPICMSST("");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setRetTransp((TNFe.InfNFe.Transp.RetTransp) null);
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Transp0.vagao = "lWV3,V";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      tNFe_InfNFe_Transp0.getTransporta();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS30 tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS30();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0.getPMVAST();
      TNFe.InfNFe.Det tNFe_InfNFe_Det0 = new TNFe.InfNFe.Det();
      tNFe_InfNFe_Det0.getObsItem();
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPICMSST("");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setRetTransp((TNFe.InfNFe.Transp.RetTransp) null);
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      tNFe_InfNFe_Transp0.getTransporta();
      TNFe.InfNFe.Cobr.Fat tNFe_InfNFe_Cobr_Fat0 = new TNFe.InfNFe.Cobr.Fat();
      tNFe_InfNFe_Cobr_Fat0.getVDesc();
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TVeiculo tVeiculo0 = tNFe_InfNFe_Transp0.veicTransp;
      tNFe_InfNFe_Transp0.setVeicTransp((TVeiculo) null);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      TNFe.InfNFe.Pag tNFe_InfNFe_Pag0 = new TNFe.InfNFe.Pag();
      tNFe_InfNFe_Pag0.vTroco = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMS15";
      tNFe_InfNFe_Pag0.vTroco = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMS15";
      tNFe_InfNFe_Pag0.getDetPag();
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setCEAN("");
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPICMSST("");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setRetTransp((TNFe.InfNFe.Transp.RetTransp) null);
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      tNFe_InfNFe_Transp0.getTransporta();
      TNFe.InfNFe.Cobr.Fat tNFe_InfNFe_Cobr_Fat0 = new TNFe.InfNFe.Cobr.Fat();
      tNFe_InfNFe_Cobr_Fat0.getVDesc();
      TNFe.InfNFe.Det.Prod.Med tNFe_InfNFe_Det_Prod_Med0 = new TNFe.InfNFe.Det.Prod.Med();
      TNFe.InfNFe.Cana tNFe_InfNFe_Cana0 = new TNFe.InfNFe.Cana();
      tNFe_InfNFe_Cana0.getForDia();
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setVICMS("br.com.swconsultoria.nfe.schema_4.enviNFe.TInfRespTec");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      TNFe.InfNFe.Total.ICMSTot tNFe_InfNFe_Total_ICMSTot0 = new TNFe.InfNFe.Total.ICMSTot();
      tNFe_InfNFe_Total_ICMSTot0.setVFCPST("^.");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS70 tNFe_InfNFe_Det_Imposto_ICMS_ICMS70_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS70();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS70_0.setPICMS("br.com.swconsultoria.nfe.schema_4.enviNFe.KeyInfoType");
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getRastro();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      TVeiculo tVeiculo0 = tNFe_InfNFe_Transp0.veicTransp;
      tNFe_InfNFe_Transp0.veicTransp = null;
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.pRedBC = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setVBCST("=C<eq=?~IM=#8SL;QCZ");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.Det.Imposto.ICMSUFDest tNFe_InfNFe_Det_Imposto_ICMSUFDest0 = new TNFe.InfNFe.Det.Imposto.ICMSUFDest();
      tNFe_InfNFe_Det_Imposto_ICMSUFDest0.getPICMSInterPart();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN201_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN201_0.getPCredSN();
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.csosn = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201";
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.getPICMS();
      TNFe.InfNFe.Det.Imposto.PISST tNFe_InfNFe_Det_Imposto_PISST0 = new TNFe.InfNFe.Det.Imposto.PISST();
      tNFe_InfNFe_Det_Imposto_PISST0.getVPIS();
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      TNFe.InfNFe.Det.Imposto.PIS.PISQtde tNFe_InfNFe_Det_Imposto_PIS_PISQtde0 = new TNFe.InfNFe.Det.Imposto.PIS.PISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN((String) null);
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setPICMSST("");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.orig = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setRetTransp((TNFe.InfNFe.Transp.RetTransp) null);
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TUf");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      tNFe_InfNFe_Transp0.getTransporta();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN201_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN201_0.getPFCPST();
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod1 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod1.getInfProdNFF();
      tNFe_InfNFe_Det_Prod0.setInfProdNFF((TNFe.InfNFe.Det.Prod.InfProdNFF) null);
      tNFe_InfNFe_Det_Prod0.setUCom("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$InfAdic");
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.pCredSN = "br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.setVagao("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS30 tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS30();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS30_0.setMotDesICMS("VT6z /I^S~|@^");
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0 = new TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde();
      tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0.cst = "";
      tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0.vAliqProd = "";
      tNFe_InfNFe_Det_Imposto_COFINS_COFINSQtde0.setVAliqProd("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSPart");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMS60 tNFe_InfNFe_Det_Imposto_ICMS_ICMS60_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMS60();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMS60_0.setVBCSTRet("V<R>p\"oaq0K=");
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.vfcpst = "";
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setCSOSN("");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN202_0.setModBCST("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      TNFe.InfNFe.Det.Imposto.PIS tNFe_InfNFe_Det_Imposto_PIS0 = new TNFe.InfNFe.Det.Imposto.PIS();
      tNFe_InfNFe_Det_Imposto_PIS0.setPISOutr((TNFe.InfNFe.Det.Imposto.PIS.PISOutr) null);
      tNFe_InfNFe_Det_Imposto_PIS0.getPISQtde();
      TNFe.InfNFe.Det.Prod tNFe_InfNFe_Det_Prod0 = new TNFe.InfNFe.Det.Prod();
      tNFe_InfNFe_Det_Prod0.indEscala = "";
      tNFe_InfNFe_Det_Prod0.getVeicProd();
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("br.com.swconsultoria.nfe.schema_4.enviNFe.TNFe$InfNFe$Det$Imposto$ICMS$ICMSSN201");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setOrig("MT");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN101_0.setCSOSN("");
      TNFe.InfNFe.Transp tNFe_InfNFe_Transp0 = new TNFe.InfNFe.Transp();
      tNFe_InfNFe_Transp0.getVeicTransp();
      tNFe_InfNFe_Transp0.veicTransp = null;
      tNFe_InfNFe_Transp0.setBalsa("lWV3,V");
      TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0 = new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setVICMS("br.com.swconsultoria.nfe.schema_4.enviNFe.TInfRespTec");
      tNFe_InfNFe_Det_Imposto_ICMS_ICMSSN900_0.setPMVAST((String) null);
  }
}
