/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 02:39:21 GMT 2024
 */

package br.com.swconsultoria.nfe.schema_4.enviNFe;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TProtNFe;
import br.com.swconsultoria.nfe.schema_4.enviNFe.TRetEnviNFe;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TRetEnviNFe_ESTest extends TRetEnviNFe_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TRetEnviNFe.InfRec tRetEnviNFe_InfRec0 = new TRetEnviNFe.InfRec();
      tRetEnviNFe_InfRec0.setTMed("yVr@Y<1E~|4ZS;");
      assertEquals("yVr@Y<1E~|4ZS;", tRetEnviNFe_InfRec0.getTMed());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TRetEnviNFe.InfRec tRetEnviNFe_InfRec0 = new TRetEnviNFe.InfRec();
      tRetEnviNFe_InfRec0.tMed = "oh<nfN`nOW/uHXiQ";
      String string0 = tRetEnviNFe_InfRec0.getTMed();
      assertEquals("oh<nfN`nOW/uHXiQ", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      TProtNFe tProtNFe0 = new TProtNFe();
      tRetEnviNFe0.setProtNFe(tProtNFe0);
      assertNull(tRetEnviNFe0.getDhRecbto());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setXMotivo("V");
      String string0 = tRetEnviNFe0.getXMotivo();
      assertEquals("V", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setXMotivo("");
      String string0 = tRetEnviNFe0.getXMotivo();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setVersao("SdV*n%BFuQ|zm");
      String string0 = tRetEnviNFe0.getVersao();
      assertEquals("SdV*n%BFuQ|zm", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setVersao("");
      String string0 = tRetEnviNFe0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setVerAplic("lB<z,y5__e");
      String string0 = tRetEnviNFe0.getVerAplic();
      assertEquals("lB<z,y5__e", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setTpAmb("H");
      String string0 = tRetEnviNFe0.getTpAmb();
      assertEquals("H", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.tpAmb = "";
      String string0 = tRetEnviNFe0.getTpAmb();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      TProtNFe tProtNFe0 = new TProtNFe();
      tRetEnviNFe0.protNFe = tProtNFe0;
      TProtNFe tProtNFe1 = tRetEnviNFe0.getProtNFe();
      assertSame(tProtNFe1, tProtNFe0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.dhRecbto = "rjY>+e:<t^5s%+N<S";
      String string0 = tRetEnviNFe0.getDhRecbto();
      assertEquals("rjY>+e:<t^5s%+N<S", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCUF("?;qZq#,A2J:\"XY6");
      String string0 = tRetEnviNFe0.getCUF();
      assertEquals("?;qZq#,A2J:\"XY6", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.cuf = "";
      String string0 = tRetEnviNFe0.getCUF();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("?;qZq#,A2J:\"XY6");
      String string0 = tRetEnviNFe0.getCStat();
      assertEquals("?;qZq#,A2J:\"XY6", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TRetEnviNFe.InfRec tRetEnviNFe_InfRec0 = new TRetEnviNFe.InfRec();
      String string0 = tRetEnviNFe_InfRec0.getNRec();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TRetEnviNFe.InfRec tRetEnviNFe_InfRec0 = new TRetEnviNFe.InfRec();
      tRetEnviNFe_InfRec0.setNRec("");
      String string0 = tRetEnviNFe_InfRec0.getNRec();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setCStat("");
      String string0 = tRetEnviNFe0.getCStat();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      TRetEnviNFe.InfRec tRetEnviNFe_InfRec0 = new TRetEnviNFe.InfRec();
      tRetEnviNFe0.setInfRec(tRetEnviNFe_InfRec0);
      TRetEnviNFe.InfRec tRetEnviNFe_InfRec1 = tRetEnviNFe0.getInfRec();
      assertNull(tRetEnviNFe_InfRec1.getNRec());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setDhRecbto("");
      String string0 = tRetEnviNFe0.getDhRecbto();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      String string0 = tRetEnviNFe0.getCUF();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      tRetEnviNFe0.setVerAplic("");
      String string0 = tRetEnviNFe0.getVerAplic();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      TProtNFe tProtNFe0 = tRetEnviNFe0.getProtNFe();
      assertNull(tProtNFe0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      TRetEnviNFe.InfRec tRetEnviNFe_InfRec0 = tRetEnviNFe0.getInfRec();
      assertNull(tRetEnviNFe_InfRec0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      String string0 = tRetEnviNFe0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      String string0 = tRetEnviNFe0.getXMotivo();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      String string0 = tRetEnviNFe0.getDhRecbto();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      String string0 = tRetEnviNFe0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      String string0 = tRetEnviNFe0.getCStat();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TRetEnviNFe tRetEnviNFe0 = new TRetEnviNFe();
      String string0 = tRetEnviNFe0.getTpAmb();
      assertNull(string0);
  }
}
