/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 07:46:01 GMT 2024
 */

package br.com.swconsultoria.nfe.schema.envEpec;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema.envEpec.TUfEmi;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TUfEmi_ESTest extends TUfEmi_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TUfEmi[] tUfEmiArray0 = TUfEmi.values();
      assertEquals(27, tUfEmiArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TUfEmi tUfEmi0 = TUfEmi.valueOf("SP");
      assertEquals(TUfEmi.SP, tUfEmi0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TUfEmi tUfEmi0 = TUfEmi.fromValue("AP");
      assertEquals(TUfEmi.AP, tUfEmi0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TUfEmi tUfEmi0 = TUfEmi.RO;
      String string0 = tUfEmi0.value();
      assertEquals("RO", string0);
  }
}
