/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 07:49:51 GMT 2024
 */

package br.com.swconsultoria.nfe.schema.eventoSuframaVistoria;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema.eventoSuframaVistoria.SignatureType;
import br.com.swconsultoria.nfe.schema.eventoSuframaVistoria.TretEvento;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TretEvento_ESTest extends TretEvento_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.id = "A-z]Bwn8io>zR*k@F";
      String string0 = tretEvento_InfEvento0.getId();
      assertEquals("A-z]Bwn8io>zR*k@F", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.nProt = "br.com.swconsultoria.nfe.schema.eventoSuframaVistoria.TransformsType";
      String string0 = tretEvento_InfEvento0.getNProt();
      assertEquals("br.com.swconsultoria.nfe.schema.eventoSuframaVistoria.TransformsType", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setDhRegEvento("");
      String string0 = tretEvento_InfEvento0.getDhRegEvento();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setNSeqEvento("9&/Kw\u0007~'m``nQJ");
      String string0 = tretEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setEmailDest("ULP_(QS'%*7");
      String string0 = tretEvento_InfEvento0.getEmailDest();
      assertEquals("ULP_(QS'%*7", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.cpfDest = "R]GBZD";
      String string0 = tretEvento_InfEvento0.getCPFDest();
      assertEquals("R]GBZD", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setNProt("xk5ix]w");
      String string0 = tretEvento_InfEvento0.getCPFDest();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setCNPJDest("G}UV9zh");
      String string0 = tretEvento_InfEvento0.getCNPJDest();
      assertEquals("G}UV9zh", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setNSeqEvento("9X'vu6Y!ai>n@UAi");
      String string0 = tretEvento_InfEvento0.getNSeqEvento();
      assertEquals("9X'vu6Y!ai>n@UAi", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setTpEvento("");
      String string0 = tretEvento_InfEvento0.getTpEvento();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.nProt = "";
      String string0 = tretEvento_InfEvento0.getChNFe();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.xMotivo = "c.]qEBl:hO'";
      String string0 = tretEvento_InfEvento0.getXMotivo();
      assertEquals("c.]qEBl:hO'", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setCStat("/zGkoj>\"p~c6:fw");
      String string0 = tretEvento_InfEvento0.getCStat();
      assertEquals("/zGkoj>\"p~c6:fw", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setCOrgao("2s");
      String string0 = tretEvento_InfEvento0.getCOrgao();
      assertEquals("2s", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setVerAplic("2s");
      String string0 = tretEvento_InfEvento0.getVerAplic();
      assertEquals("2s", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setTpAmb("");
      assertNull(tretEvento_InfEvento0.getNProt());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.tpAmb = "IY {D+~NcHV{";
      String string0 = tretEvento_InfEvento0.getTpAmb();
      assertEquals("IY {D+~NcHV{", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TretEvento tretEvento0 = new TretEvento();
      tretEvento0.versao = "hr{BBTYHan2A A^I~d?";
      String string0 = tretEvento0.getVersao();
      assertEquals("hr{BBTYHan2A A^I~d?", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TretEvento tretEvento0 = new TretEvento();
      tretEvento0.setVersao("");
      String string0 = tretEvento0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TretEvento tretEvento0 = new TretEvento();
      SignatureType signatureType0 = new SignatureType();
      tretEvento0.signature = signatureType0;
      SignatureType signatureType1 = tretEvento0.getSignature();
      assertSame(signatureType1, signatureType0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setXEvento("oN$UiK|&qx\"O");
      String string0 = tretEvento_InfEvento0.getXEvento();
      assertEquals("oN$UiK|&qx\"O", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setCPFDest("");
      assertNull(tretEvento_InfEvento0.getXMotivo());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setChNFe("");
      String string0 = tretEvento_InfEvento0.getChNFe();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setXMotivo("br.com.swconsultoria.nfe.schema.eventoSuframaVistoria.TransformType");
      assertNull(tretEvento_InfEvento0.getCPFDest());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      tretEvento_InfEvento0.setId(".2(o}`Ruvpz-N&Jq");
      assertNull(tretEvento_InfEvento0.getTpAmb());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TretEvento tretEvento0 = new TretEvento();
      SignatureType signatureType0 = new SignatureType();
      tretEvento0.setSignature(signatureType0);
      assertNull(tretEvento0.getVersao());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TretEvento tretEvento0 = new TretEvento();
      String string0 = tretEvento0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TretEvento tretEvento0 = new TretEvento();
      SignatureType signatureType0 = tretEvento0.getSignature();
      assertNull(signatureType0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TretEvento.InfEvento tretEvento_InfEvento0 = new TretEvento.InfEvento();
      TretEvento tretEvento0 = new TretEvento();
      tretEvento0.setInfEvento(tretEvento_InfEvento0);
      TretEvento.InfEvento tretEvento_InfEvento1 = tretEvento0.getInfEvento();
      assertNull(tretEvento_InfEvento1.getXEvento());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TretEvento tretEvento0 = new TretEvento();
      TretEvento.InfEvento tretEvento_InfEvento0 = tretEvento0.getInfEvento();
      assertNull(tretEvento_InfEvento0);
  }
}
