/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 11:48:46 GMT 2024
 */

package br.com.swconsultoria.nfe.schema.envcce;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema.envcce.TRetEnvEvento;
import br.com.swconsultoria.nfe.schema.envcce.TretEvento;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TRetEnvEvento_ESTest extends TRetEnvEvento_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.setXMotivo("W!Cv@c[");
      String string0 = tRetEnvEvento0.getXMotivo();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.setXMotivo("");
      String string0 = tRetEnvEvento0.getXMotivo();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.setVersao(")P/\"\",i(");
      String string0 = tRetEnvEvento0.getVersao();
      assertEquals(")P/\"\",i(", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.setVersao("");
      String string0 = tRetEnvEvento0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.setVerAplic("br.com.swconsultoria.nfe.schema.envcce.ReferenceType$DigestMethod");
      String string0 = tRetEnvEvento0.getVerAplic();
      assertEquals("br.com.swconsultoria.nfe.schema.envcce.ReferenceType$DigestMethod", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.verAplic = "";
      String string0 = tRetEnvEvento0.getVerAplic();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.setTpAmb("$Na");
      String string0 = tRetEnvEvento0.getTpAmb();
      assertEquals("$Na", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.tpAmb = "";
      String string0 = tRetEnvEvento0.getTpAmb();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      LinkedList<TretEvento> linkedList0 = new LinkedList<TretEvento>();
      TretEvento tretEvento0 = new TretEvento();
      linkedList0.offerFirst(tretEvento0);
      tRetEnvEvento0.retEvento = (List<TretEvento>) linkedList0;
      List<TretEvento> list0 = tRetEnvEvento0.getRetEvento();
      assertTrue(list0.contains(tretEvento0));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.setIdLote("br.com.swconsultoria.nfe.schema.envcce.TRetEnvEvento");
      String string0 = tRetEnvEvento0.getIdLote();
      assertEquals("br.com.swconsultoria.nfe.schema.envcce.TRetEnvEvento", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.idLote = "";
      String string0 = tRetEnvEvento0.getIdLote();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.setCStat("|=.XX{B!`2k:l_0");
      String string0 = tRetEnvEvento0.getCStat();
      assertEquals("|=.XX{B!`2k:l_0", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.cStat = "";
      String string0 = tRetEnvEvento0.getCStat();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.setCOrgao("e(lwg!f?c");
      String string0 = tRetEnvEvento0.getCOrgao();
      assertEquals("e(lwg!f?c", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.cOrgao = "";
      String string0 = tRetEnvEvento0.getCOrgao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      tRetEnvEvento0.getRetEvento();
      List<TretEvento> list0 = tRetEnvEvento0.getRetEvento();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      String string0 = tRetEnvEvento0.getTpAmb();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      String string0 = tRetEnvEvento0.getIdLote();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      String string0 = tRetEnvEvento0.getXMotivo();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      String string0 = tRetEnvEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      String string0 = tRetEnvEvento0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      String string0 = tRetEnvEvento0.getCStat();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TRetEnvEvento tRetEnvEvento0 = new TRetEnvEvento();
      String string0 = tRetEnvEvento0.getCOrgao();
      assertNull(string0);
  }
}
