/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 11:13:34 GMT 2024
 */

package br.com.swconsultoria.nfe.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.exception.NfeValidacaoException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NfeValidacaoException_ESTest extends NfeValidacaoException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NfeValidacaoException nfeValidacaoException0 = new NfeValidacaoException("4G.^DL$wG&V,>");
      nfeValidacaoException0.setMessage((String) null);
      String string0 = nfeValidacaoException0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NfeValidacaoException nfeValidacaoException0 = new NfeValidacaoException("4G.^DL$wG&V,>");
      String string0 = nfeValidacaoException0.getMessage();
      assertEquals("4G.^DL$wG&V,>", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("");
      NfeValidacaoException nfeValidacaoException0 = new NfeValidacaoException(mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NfeValidacaoException nfeValidacaoException0 = new NfeValidacaoException("");
      String string0 = nfeValidacaoException0.getMessage();
      assertEquals("", string0);
  }
}
