/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 12:07:59 GMT 2024
 */

package br.com.swconsultoria.certificado.util;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.certificado.util.CacertUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CacertUtil_ESTest extends CacertUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[3];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\Program Files\\Java\\jdk1.8.0_301\\jre\\lib\\security\\cacerts");
      byte[] byteArray0 = new byte[4];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      CacertUtil.main(stringArray0);
      assertEquals(3, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CacertUtil cacertUtil0 = new CacertUtil();
  }
}
