/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 09:49:16 GMT 2024
 */

package br.com.swconsultoria.nfe.schema_4.retConsStatServ;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema_4.retConsStatServ.TRetConsStatServ;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TRetConsStatServ_ESTest extends TRetConsStatServ_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.xObs = "z95?WweD";
      String string0 = tRetConsStatServ0.getXObs();
      assertEquals("z95?WweD", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setXObs("");
      String string0 = tRetConsStatServ0.getXObs();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setXMotivo("\"I(~J-evpDl`(?h[|_U");
      String string0 = tRetConsStatServ0.getXMotivo();
      assertEquals("\"I(~J-evpDl`(?h[|_U", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.xMotivo = "";
      String string0 = tRetConsStatServ0.getXMotivo();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setVersao(",(oLp>`GF=+uqabC]]!");
      String string0 = tRetConsStatServ0.getVersao();
      assertEquals(",(oLp>`GF=+uqabC]]!", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.versao = null;
      tRetConsStatServ0.versao = "";
      String string0 = tRetConsStatServ0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setVerAplic(")JL(Sa{wPRW");
      String string0 = tRetConsStatServ0.getVerAplic();
      assertEquals(")JL(Sa{wPRW", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setVerAplic("");
      String string0 = tRetConsStatServ0.getVerAplic();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setTpAmb("B{qfQsBY");
      String string0 = tRetConsStatServ0.getTpAmb();
      assertEquals("B{qfQsBY", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setTMed("z95?WweD");
      String string0 = tRetConsStatServ0.getTMed();
      assertEquals("z95?WweD", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setTMed("");
      String string0 = tRetConsStatServ0.getTMed();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.dhRetorno = "H8=I'hk9dH3";
      String string0 = tRetConsStatServ0.getDhRetorno();
      assertEquals("H8=I'hk9dH3", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.dhRetorno = "";
      String string0 = tRetConsStatServ0.getDhRetorno();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setDhRecbto("lJCtLgHf]D-M#l)'@>");
      String string0 = tRetConsStatServ0.getDhRecbto();
      assertEquals("lJCtLgHf]D-M#l)'@>", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.cuf = "$+_ISmA'uW?G@";
      String string0 = tRetConsStatServ0.getCUF();
      assertEquals("$+_ISmA'uW?G@", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setCStat("pr&t_%h)2zFfI");
      String string0 = tRetConsStatServ0.getCStat();
      assertEquals("pr&t_%h)2zFfI", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      String string0 = tRetConsStatServ0.getCUF();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      String string0 = tRetConsStatServ0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setDhRecbto("");
      String string0 = tRetConsStatServ0.getDhRecbto();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      String string0 = tRetConsStatServ0.getDhRetorno();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      String string0 = tRetConsStatServ0.getCStat();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      String string0 = tRetConsStatServ0.getDhRecbto();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      String string0 = tRetConsStatServ0.getTpAmb();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setCUF("");
      String string0 = tRetConsStatServ0.getCUF();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setTpAmb("");
      String string0 = tRetConsStatServ0.getTpAmb();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      String string0 = tRetConsStatServ0.getXMotivo();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      String string0 = tRetConsStatServ0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setDhRetorno("");
      assertNull(tRetConsStatServ0.getVerAplic());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      String string0 = tRetConsStatServ0.getTMed();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      tRetConsStatServ0.setCStat("");
      String string0 = tRetConsStatServ0.getCStat();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      String string0 = tRetConsStatServ0.getXObs();
      assertNull(string0);
  }
}
