/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 08:57:28 GMT 2024
 */

package br.com.swconsultoria.nfe.schema.retEnvEventoCancNFe;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema.retEnvEventoCancNFe.SignatureType;
import br.com.swconsultoria.nfe.schema.retEnvEventoCancNFe.TRetEvento;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TRetEvento_ESTest extends TRetEvento_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.id = "&=";
      String string0 = tRetEvento_InfEvento0.getId();
      assertEquals("&=", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNProt("");
      String string0 = tRetEvento_InfEvento0.getNProt();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setEmailDest("");
      String string0 = tRetEvento_InfEvento0.getEmailDest();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setChNFe("br.com.swconsultoria.nfe.schema.retEnvEventoCancNFe.TRetEvento$InfEvento");
      String string0 = tRetEvento_InfEvento0.getEmailDest();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setVerAplic("");
      String string0 = tRetEvento_InfEvento0.getEmailDest();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNSeqEvento("");
      String string0 = tRetEvento_InfEvento0.getEmailDest();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCPFDest("MG[f&UZ@pDs.L}7o*");
      String string0 = tRetEvento_InfEvento0.getCPFDest();
      assertEquals("MG[f&UZ@pDs.L}7o*", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      tRetEvento_InfEvento0.setCNPJDest("");
      String string0 = tRetEvento0.infEvento.getCNPJDest();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.tpEvento = "@GXzsHMLp'";
      String string0 = tRetEvento_InfEvento0.getTpEvento();
      assertEquals("@GXzsHMLp'", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.chNFe = "lkb";
      String string0 = tRetEvento_InfEvento0.getChNFe();
      assertEquals("lkb", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.xMotivo = "";
      String string0 = tRetEvento_InfEvento0.getXMotivo();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.cStat = "";
      String string0 = tRetEvento_InfEvento0.getCStat();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCOrgao("");
      assertNull(tRetEvento_InfEvento0.getCStat());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.cOrgao = "sV}[iJB$t|nPgS";
      String string0 = tRetEvento_InfEvento0.getCOrgao();
      assertEquals("sV}[iJB$t|nPgS", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXMotivo("QYwM;9k'x@et!N");
      String string0 = tRetEvento_InfEvento0.getCOrgao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.tpAmb = ":f{5osZ^|#YKBNK#fG";
      String string0 = tRetEvento_InfEvento0.getTpAmb();
      assertEquals(":f{5osZ^|#YKBNK#fG", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.versao = "/3";
      String string0 = tRetEvento0.getVersao();
      assertEquals("/3", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.versao = "";
      String string0 = tRetEvento0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      SignatureType signatureType0 = new SignatureType();
      tRetEvento0.signature = signatureType0;
      SignatureType signatureType1 = tRetEvento0.getSignature();
      assertNull(signatureType1.getId());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      TRetEvento.InfEvento tRetEvento_InfEvento1 = tRetEvento0.getInfEvento();
      assertNull(tRetEvento_InfEvento1.getId());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.setInfEvento(tRetEvento_InfEvento0);
      assertNull(tRetEvento_InfEvento0.getXEvento());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      String string0 = tRetEvento0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      SignatureType signatureType0 = tRetEvento0.getSignature();
      assertNull(signatureType0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.setVersao("");
      assertEquals("", tRetEvento0.getVersao());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      SignatureType signatureType0 = new SignatureType();
      tRetEvento0.setSignature(signatureType0);
      assertNull(tRetEvento0.getVersao());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = tRetEvento0.getInfEvento();
      assertNull(tRetEvento_InfEvento0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXEvento("");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setVerAplic("");
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setTpAmb("");
      assertNull(tRetEvento_InfEvento0.getDhRegEvento());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNSeqEvento("");
      String string0 = tRetEvento_InfEvento0.getNSeqEvento();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCStat("");
      assertNull(tRetEvento_InfEvento0.getCNPJDest());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setId("br.com.swconsultoria.nfe.schema.retEnvEventoCancNFe.SignatureValueType");
      assertNull(tRetEvento_InfEvento0.getDhRegEvento());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setTpEvento("Zo[yA$^meI-_L");
      assertNull(tRetEvento_InfEvento0.getChNFe());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setDhRegEvento("f^Pi3mp{).:^3(^-");
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertEquals("f^Pi3mp{).:^3(^-", string0);
  }
}
