/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 07:07:09 GMT 2024
 */

package br.com.swconsultoria.nfe.schema.retEnvEventoAtorInteressado;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema.retEnvEventoAtorInteressado.TransformType;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TransformType_ESTest extends TransformType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TransformType transformType0 = new TransformType();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("^WuI");
      transformType0.xPath = (List<String>) linkedList0;
      List<String> list0 = transformType0.getXPath();
      assertTrue(list0.contains("^WuI"));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TransformType transformType0 = new TransformType();
      transformType0.algorithm = "T6auw9JG(Rw(2Hg5";
      String string0 = transformType0.getAlgorithm();
      assertEquals("T6auw9JG(Rw(2Hg5", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TransformType transformType0 = new TransformType();
      transformType0.setAlgorithm("");
      String string0 = transformType0.getAlgorithm();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TransformType transformType0 = new TransformType();
      transformType0.getXPath();
      List<String> list0 = transformType0.getXPath();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TransformType transformType0 = new TransformType();
      String string0 = transformType0.getAlgorithm();
      assertNull(string0);
  }
}
