/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 08:26:25 GMT 2024
 */

package br.com.swconsultoria.nfe.schema.retEnvEventoAtorInteressado;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema.retEnvEventoAtorInteressado.SignatureType;
import br.com.swconsultoria.nfe.schema.retEnvEventoAtorInteressado.TRetEvento;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TRetEvento_ESTest extends TRetEvento_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setId("\")9_QSvpJ");
      String string0 = tRetEvento_InfEvento0.getId();
      assertEquals("\")9_QSvpJ", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.cOrgaoAutor = "\"ce^N)";
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      String string0 = tRetEvento0.infEvento.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setVerAplic("br.com.swconsultoria.nfe.schema.retEnvEventoAtorInteressado.ReferenceType");
      String string0 = tRetEvento_InfEvento0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNSeqEvento("");
      String string0 = tRetEvento_InfEvento0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNProt("T6pF6\"\"G$_5=)1");
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      String string0 = tRetEvento0.infEvento.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNProt("\"Ao_&bn_oivbf");
      String string0 = tRetEvento_InfEvento0.getNProt();
      assertEquals("\"Ao_&bn_oivbf", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setDhRegEvento("");
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.cOrgaoAutor = "\"ce^N)";
      String string0 = tRetEvento_InfEvento0.getCOrgaoAutor();
      assertEquals("\"ce^N)", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.xEvento = ".";
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertEquals(".", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setTpEvento("");
      assertNull(tRetEvento_InfEvento0.getXEvento());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      tRetEvento0.infEvento.tpEvento = "e=7o[$9 ";
      String string0 = tRetEvento0.infEvento.getTpEvento();
      assertEquals("e=7o[$9 ", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXMotivo("~$i\"");
      String string0 = tRetEvento_InfEvento0.getXMotivo();
      assertEquals("~$i\"", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCStat("(iv8EsOW=0BB(2PQe!x");
      assertEquals("(iv8EsOW=0BB(2PQe!x", tRetEvento_InfEvento0.getCStat());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.cStat = "%j*+";
      String string0 = tRetEvento_InfEvento0.getCStat();
      assertEquals("%j*+", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCOrgao("v,5:p");
      String string0 = tRetEvento_InfEvento0.getCOrgao();
      assertEquals("v,5:p", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.verAplic = "MHd}zo>s";
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertEquals("MHd}zo>s", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.versao = "k.()QH\"1F_3c%b";
      String string0 = tRetEvento0.getVersao();
      assertEquals("k.()QH\"1F_3c%b", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.setVersao("");
      String string0 = tRetEvento0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      TRetEvento.InfEvento tRetEvento_InfEvento1 = tRetEvento0.getInfEvento();
      assertSame(tRetEvento_InfEvento1, tRetEvento_InfEvento0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      String string0 = tRetEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setTpAmb("K#hAe#e:qUm ui");
      String string0 = tRetEvento_InfEvento0.getTpAmb();
      assertEquals("K#hAe#e:qUm ui", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setChNFe("");
      String string0 = tRetEvento_InfEvento0.getChNFe();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNSeqEvento("x}QcDT.M(s>^-TH,Se");
      String string0 = tRetEvento_InfEvento0.getNSeqEvento();
      assertEquals("x}QcDT.M(s>^-TH,Se", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXEvento("");
      assertNull(tRetEvento_InfEvento0.getChNFe());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCOrgaoAutor("br.com.swconsultoria.nfe.schema.retEnvEventoAtorInteressado.SignatureType");
      assertNull(tRetEvento_InfEvento0.getXMotivo());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.setInfEvento(tRetEvento_InfEvento0);
      assertNull(tRetEvento_InfEvento0.getCStat());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      String string0 = tRetEvento0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      SignatureType signatureType0 = tRetEvento0.getSignature();
      assertNull(signatureType0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = tRetEvento0.getInfEvento();
      assertNull(tRetEvento_InfEvento0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      SignatureType signatureType0 = new SignatureType();
      tRetEvento0.setSignature(signatureType0);
      SignatureType signatureType1 = tRetEvento0.getSignature();
      assertSame(signatureType1, signatureType0);
  }
}
