/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 10:00:13 GMT 2024
 */

package br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.SignatureType;
import br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TEvento;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TEvento_ESTest extends TEvento_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setVersao("");
      String string0 = tEvento_InfEvento_DetEvento0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento0.setDetEvento(tEvento_InfEvento_DetEvento0);
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento1 = tEvento_InfEvento0.getDetEvento();
      tEvento_InfEvento_DetEvento1.dVistoria = "";
      String string0 = tEvento_InfEvento_DetEvento1.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setXHistorico(".Yw?G@9#1+9TS)=6$]_");
      String string0 = tEvento_InfEvento_DetEvento0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setVersao("Q!EiG<$+Pi|=lQ$p");
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.detEvento = tEvento_InfEvento_DetEvento0;
      String string0 = tEvento_InfEvento0.detEvento.getXHistorico();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setPostoVistoria("Q!EiG<$+Pi|=lQ$p");
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.detEvento = tEvento_InfEvento_DetEvento0;
      String string0 = tEvento_InfEvento0.detEvento.getXHistorico();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.locVistoria = "i2xzlu<]%h]:*9";
      String string0 = tEvento_InfEvento_DetEvento0.getXHistorico();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.descEvento = "<4<=W(UQ~vS/H";
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.detEvento = tEvento_InfEvento_DetEvento0;
      String string0 = tEvento_InfEvento0.detEvento.getXHistorico();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.piNe = "";
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.detEvento = tEvento_InfEvento_DetEvento0;
      String string0 = tEvento_InfEvento0.detEvento.getXHistorico();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setDVistoria("c8.]]wN47it<");
      String string0 = tEvento_InfEvento_DetEvento0.getXHistorico();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setPostoVistoria("Q!EiG<$+Pi|=lQ$p");
      String string0 = tEvento_InfEvento_DetEvento0.getPostoVistoria();
      assertEquals("Q!EiG<$+Pi|=lQ$p", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setLocVistoria("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TEvento$InfEvento$DetEvento");
      String string0 = tEvento_InfEvento_DetEvento0.getLocVistoria();
      assertEquals("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TEvento$InfEvento$DetEvento", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.dVistoria = "br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TransformType";
      String string0 = tEvento_InfEvento_DetEvento0.getDVistoria();
      assertEquals("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TransformType", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setVersao("r|'cL|PyO8");
      String string0 = tEvento_InfEvento_DetEvento0.getPINe();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setPostoVistoria(".Yw?G@9#1+9TS)=6$]_");
      String string0 = tEvento_InfEvento_DetEvento0.getPINe();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setLocVistoria("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TEvento$InfEvento$DetEvento");
      String string0 = tEvento_InfEvento_DetEvento0.getPINe();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.descEvento = "oSk`FCxxDqhM4X";
      String string0 = tEvento_InfEvento_DetEvento0.getPINe();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setXHistorico(".Yw?G@9#1+9TS)=6$]_");
      String string0 = tEvento_InfEvento_DetEvento0.getPINe();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setDescEvento("$C!.0hv6Mm*U'.5");
      String string0 = tEvento_InfEvento_DetEvento0.getDescEvento();
      assertEquals("$C!.0hv6Mm*U'.5", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento_DetEvento0.setPINe("");
      String string0 = tEvento_InfEvento_DetEvento0.getDescEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setId("http://www.w3.org/2000/09/xmldsig#sha1");
      String string0 = tEvento_InfEvento0.getId();
      assertEquals("http://www.w3.org/2000/09/xmldsig#sha1", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setCOrgao("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TEvento");
      String string0 = tEvento_InfEvento0.getVerEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setTpEvento("*M4JVXcP25]k+,+Y");
      String string0 = tEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.verEvento = "[";
      String string0 = tEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.tpAmb = "i2xzlu<]%h]:*9";
      String string0 = tEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TEvento tEvento0 = new TEvento();
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento0.infEvento = tEvento_InfEvento0;
      TEvento.InfEvento tEvento_InfEvento1 = tEvento0.getInfEvento();
      tEvento_InfEvento1.cnpj = "br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TEvento$InfEvento$DetEvento";
      String string0 = tEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setChNFe(":");
      String string0 = tEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setCPF(":");
      String string0 = tEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.dhEvento = "";
      String string0 = tEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.cOrgao = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
      String string0 = tEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.tpEvento = "";
      String string0 = tEvento_InfEvento0.getTpEvento();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setDhEvento("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TransformType");
      String string0 = tEvento_InfEvento0.getDhEvento();
      assertEquals("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TransformType", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setCOrgao("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TEvento");
      String string0 = tEvento_InfEvento0.getChNFe();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setCOrgao("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TEvento");
      String string0 = tEvento_InfEvento0.getCPF();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setCNPJ("#te3\"Q&");
      TEvento tEvento0 = new TEvento();
      tEvento0.infEvento = tEvento_InfEvento0;
      String string0 = tEvento0.infEvento.getCNPJ();
      assertEquals("#te3\"Q&", string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setTpAmb("PLJuFR_e!v");
      String string0 = tEvento_InfEvento0.getTpAmb();
      assertEquals("PLJuFR_e!v", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      TEvento tEvento0 = new TEvento();
      tEvento0.setVersao("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TransformType");
      String string0 = tEvento0.getVersao();
      assertEquals("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TransformType", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      TEvento tEvento0 = new TEvento();
      SignatureType signatureType0 = new SignatureType();
      tEvento0.signature = signatureType0;
      SignatureType signatureType1 = tEvento0.getSignature();
      assertSame(signatureType1, signatureType0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento0 = new TEvento.InfEvento.DetEvento();
      tEvento_InfEvento0.setDetEvento(tEvento_InfEvento_DetEvento0);
      TEvento.InfEvento.DetEvento tEvento_InfEvento_DetEvento1 = tEvento_InfEvento0.getDetEvento();
      tEvento_InfEvento_DetEvento1.dVistoria = "";
      String string0 = tEvento_InfEvento_DetEvento0.getPINe();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setCOrgao("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TEvento");
      String string0 = tEvento_InfEvento0.getCOrgao();
      assertEquals("br.com.swconsultoria.nfe.schema.eventoSuframaInternaliza.TEvento", string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setId("77sbM5|g/");
      String string0 = tEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setCPF("");
      String string0 = tEvento_InfEvento0.getCPF();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      TEvento tEvento0 = new TEvento();
      tEvento0.infEvento = tEvento_InfEvento0;
      tEvento0.infEvento.setVerEvento("");
      String string0 = tEvento_InfEvento0.getVerEvento();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setNSeqEvento("U/t8");
      assertNull(tEvento_InfEvento0.getVerEvento());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      tEvento_InfEvento0.setChNFe("iCoFo`#");
      TEvento tEvento0 = new TEvento();
      tEvento0.infEvento = tEvento_InfEvento0;
      String string0 = tEvento0.infEvento.getChNFe();
      assertEquals("iCoFo`#", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      TEvento tEvento0 = new TEvento();
      SignatureType signatureType0 = tEvento0.getSignature();
      assertNull(signatureType0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      TEvento tEvento0 = new TEvento();
      tEvento0.setVersao("");
      String string0 = tEvento0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      TEvento.InfEvento tEvento_InfEvento0 = new TEvento.InfEvento();
      TEvento tEvento0 = new TEvento();
      tEvento0.setInfEvento(tEvento_InfEvento0);
      TEvento.InfEvento tEvento_InfEvento1 = tEvento0.getInfEvento();
      assertNull(tEvento_InfEvento1.getTpEvento());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      TEvento tEvento0 = new TEvento();
      String string0 = tEvento0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      TEvento tEvento0 = new TEvento();
      SignatureType signatureType0 = new SignatureType();
      tEvento0.setSignature(signatureType0);
      assertNull(signatureType0.getId());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      TEvento tEvento0 = new TEvento();
      TEvento.InfEvento tEvento_InfEvento0 = tEvento0.getInfEvento();
      assertNull(tEvento_InfEvento0);
  }
}
