/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 11:39:35 GMT 2024
 */

package br.com.swconsultoria.nfe.schema.retenvcce;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema.retenvcce.TEvento;
import br.com.swconsultoria.nfe.schema.retenvcce.TProcEvento;
import br.com.swconsultoria.nfe.schema.retenvcce.TretEvento;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TProcEvento_ESTest extends TProcEvento_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TProcEvento tProcEvento0 = new TProcEvento();
      tProcEvento0.setVersao("* Y~?PFd(s+PO}L4$");
      String string0 = tProcEvento0.getVersao();
      assertEquals("* Y~?PFd(s+PO}L4$", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TProcEvento tProcEvento0 = new TProcEvento();
      tProcEvento0.setVersao("");
      String string0 = tProcEvento0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TProcEvento tProcEvento0 = new TProcEvento();
      TretEvento tretEvento0 = new TretEvento();
      tProcEvento0.setRetEvento(tretEvento0);
      TretEvento tretEvento1 = tProcEvento0.getRetEvento();
      assertNull(tretEvento1.getVersao());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TProcEvento tProcEvento0 = new TProcEvento();
      TEvento tEvento0 = tProcEvento0.getEvento();
      assertNull(tEvento0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TProcEvento tProcEvento0 = new TProcEvento();
      String string0 = tProcEvento0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TProcEvento tProcEvento0 = new TProcEvento();
      TretEvento tretEvento0 = tProcEvento0.getRetEvento();
      assertNull(tretEvento0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TProcEvento tProcEvento0 = new TProcEvento();
      TEvento tEvento0 = new TEvento();
      tProcEvento0.setEvento(tEvento0);
      TEvento tEvento1 = tProcEvento0.getEvento();
      assertSame(tEvento1, tEvento0);
  }
}
