/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 08:23:40 GMT 2024
 */

package br.com.swconsultoria.nfe.schema.epec;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema.epec.SignatureType;
import br.com.swconsultoria.nfe.schema.epec.TRetEvento;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TRetEvento_ESTest extends TRetEvento_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.id = "";
      String string0 = tRetEvento_InfEvento0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.dhRegEvento = "br.com.swconsultoria.nfe.schema.epec.SignedInfoType$CanonicalizationMethod";
      String string0 = tRetEvento_InfEvento0.getDhRegEvento();
      assertEquals("br.com.swconsultoria.nfe.schema.epec.SignedInfoType$CanonicalizationMethod", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNSeqEvento("(F38");
      String string0 = tRetEvento_InfEvento0.getNSeqEvento();
      assertEquals("(F38", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setChNFe("s*E3=#'");
      String string0 = tRetEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setVerAplic("s*E3=#'");
      String string0 = tRetEvento_InfEvento0.getNSeqEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setTpEvento("Zc@<J8(BIcIE");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setId("br.com.swconsultoria.nfe.schema.epec.TRetEvento");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      tRetEvento0.infEvento.setCOrgao("");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.cStat = "vZ]taWES!k16W W";
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXMotivo("br.com.swconsultoria.nfe.schema.epec.SignedInfoType");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.cOrgaoAutor = "s*E3=#'";
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setVerAplic("4wUgK_J,fk0nF}!a");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      tRetEvento_InfEvento0.setNSeqEvento("");
      String string0 = tRetEvento0.infEvento.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNProt("br.com.swconsultoria.nfe.schema.epec.TRetEvento");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.chNFe = "";
      String string0 = tRetEvento_InfEvento0.getChNFe();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCOrgaoAutor("9w");
      String string0 = tRetEvento_InfEvento0.getChNFe();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.xMotivo = null;
      tRetEvento_InfEvento0.xMotivo = "br.com.swconsultoria.nfe.schema.epec.TRetEvento$InfEvento";
      String string0 = tRetEvento_InfEvento0.getXMotivo();
      assertEquals("br.com.swconsultoria.nfe.schema.epec.TRetEvento$InfEvento", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      tRetEvento0.infEvento.setCStat("I");
      String string0 = tRetEvento_InfEvento0.getCStat();
      assertEquals("I", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      tRetEvento0.infEvento.setCOrgao("");
      String string0 = tRetEvento_InfEvento0.getCOrgao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.tpAmb = "br.com.swconsultoria.nfe.schema.epec.TRetEvento";
      String string0 = tRetEvento_InfEvento0.getTpAmb();
      assertEquals("br.com.swconsultoria.nfe.schema.epec.TRetEvento", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.versao = "br.com.swconsultoria.nfe.schema.epec.TRetEvento$InfEvento";
      String string0 = tRetEvento0.getVersao();
      assertEquals("br.com.swconsultoria.nfe.schema.epec.TRetEvento$InfEvento", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.versao = null;
      tRetEvento0.versao = "";
      String string0 = tRetEvento0.getVersao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento0.infEvento = tRetEvento_InfEvento0;
      TRetEvento.InfEvento tRetEvento_InfEvento1 = tRetEvento0.getInfEvento();
      assertNull(tRetEvento_InfEvento1.getId());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.getChNFePend();
      List<String> list0 = tRetEvento_InfEvento0.getChNFePend();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.setInfEvento(tRetEvento_InfEvento0);
      assertNull(tRetEvento_InfEvento0.getCStat());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      String string0 = tRetEvento0.getVersao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      SignatureType signatureType0 = new SignatureType();
      tRetEvento0.setSignature(signatureType0);
      SignatureType signatureType1 = tRetEvento0.getSignature();
      assertNull(signatureType1.getId());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      tRetEvento0.setVersao("h7I@GnLTJeM?*?(");
      assertEquals("h7I@GnLTJeM?*?(", tRetEvento0.getVersao());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      SignatureType signatureType0 = tRetEvento0.getSignature();
      assertNull(signatureType0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TRetEvento tRetEvento0 = new TRetEvento();
      TRetEvento.InfEvento tRetEvento_InfEvento0 = tRetEvento0.getInfEvento();
      assertNull(tRetEvento_InfEvento0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setDhRegEvento("h7I@GnLTJeM?*?(");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setTpEvento("'~tHi");
      String string0 = tRetEvento_InfEvento0.getTpEvento();
      assertEquals("'~tHi", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setChNFe("s*E3=#'");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setXEvento("");
      assertNull(tRetEvento_InfEvento0.getXMotivo());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setNProt(",!s0");
      String string0 = tRetEvento_InfEvento0.getNProt();
      assertEquals(",!s0", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setVerAplic("s*E3=#'");
      String string0 = tRetEvento_InfEvento0.getVerAplic();
      assertEquals("s*E3=#'", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setCOrgaoAutor("br.com.swconsultoria.nfe.schema.epec.KeyInfoType");
      String string0 = tRetEvento_InfEvento0.getCOrgaoAutor();
      assertEquals("br.com.swconsultoria.nfe.schema.epec.KeyInfoType", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      TRetEvento.InfEvento tRetEvento_InfEvento0 = new TRetEvento.InfEvento();
      tRetEvento_InfEvento0.setTpAmb("br.com.swconsultoria.nfe.schema.epec.TRetEvento");
      String string0 = tRetEvento_InfEvento0.getXEvento();
      assertNull(string0);
  }
}
