/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 07:38:13 GMT 2024
 */

package br.com.swconsultoria.nfe;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.swconsultoria.nfe.ConsultaCadastro;
import br.com.swconsultoria.nfe.dom.ConfiguracoesNfe;
import br.com.swconsultoria.nfe.dom.enuns.EstadosEnum;
import br.com.swconsultoria.nfe.dom.enuns.PessoaEnum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConsultaCadastro_ESTest extends ConsultaCadastro_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PessoaEnum pessoaEnum0 = PessoaEnum.JURIDICA;
      EstadosEnum estadosEnum0 = EstadosEnum.SP;
      // Undeclared exception!
      try { 
        ConsultaCadastro.consultaCadastro((ConfiguracoesNfe) null, pessoaEnum0, "g9P)k{+RvJ}*i'w@J)", estadosEnum0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.ConsultaCadastro", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConfiguracoesNfe configuracoesNfe0 = new ConfiguracoesNfe();
      PessoaEnum pessoaEnum0 = PessoaEnum.JURIDICA;
      EstadosEnum estadosEnum0 = EstadosEnum.PA;
      // Undeclared exception!
      try { 
        ConsultaCadastro.consultaCadastro(configuracoesNfe0, pessoaEnum0, "k$", estadosEnum0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/axiom/om/util/AXIOMUtil
         //
         verifyException("br.com.swconsultoria.nfe.ConsultaCadastro", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConfiguracoesNfe configuracoesNfe0 = new ConfiguracoesNfe();
      PessoaEnum pessoaEnum0 = PessoaEnum.FISICA;
      EstadosEnum estadosEnum0 = EstadosEnum.SE;
      // Undeclared exception!
      try { 
        ConsultaCadastro.consultaCadastro(configuracoesNfe0, pessoaEnum0, "EPw;,a>o", estadosEnum0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/axiom/om/util/AXIOMUtil
         //
         verifyException("br.com.swconsultoria.nfe.ConsultaCadastro", e);
      }
  }
}
