/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 11:37:26 GMT 2024
 */

package br.com.swconsultoria.nfe;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.swconsultoria.nfe.ConsultaRecibo;
import br.com.swconsultoria.nfe.dom.ConfiguracoesNfe;
import br.com.swconsultoria.nfe.dom.enuns.AmbienteEnum;
import br.com.swconsultoria.nfe.dom.enuns.DocumentoEnum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConsultaRecibo_ESTest extends ConsultaRecibo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConfiguracoesNfe configuracoesNfe0 = new ConfiguracoesNfe();
      DocumentoEnum documentoEnum0 = DocumentoEnum.NFE;
      // Undeclared exception!
      try { 
        ConsultaRecibo.reciboNfe(configuracoesNfe0, "i~M}o:DhJxUQw7", documentoEnum0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.swconsultoria.nfe.ConsultaRecibo", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConfiguracoesNfe configuracoesNfe0 = new ConfiguracoesNfe();
      AmbienteEnum ambienteEnum0 = AmbienteEnum.HOMOLOGACAO;
      configuracoesNfe0.setAmbiente(ambienteEnum0);
      DocumentoEnum documentoEnum0 = DocumentoEnum.NFE;
      // Undeclared exception!
      try { 
        ConsultaRecibo.reciboNfe(configuracoesNfe0, "/.n", documentoEnum0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/axiom/om/util/AXIOMUtil
         //
         verifyException("br.com.swconsultoria.nfe.ConsultaRecibo", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConsultaRecibo consultaRecibo0 = new ConsultaRecibo();
  }
}
