/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 11:28:48 GMT 2024
 */

package br.com.swconsultoria.nfe.schema_4.retConsStatServ;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.swconsultoria.nfe.schema_4.retConsStatServ.ObjectFactory;
import br.com.swconsultoria.nfe.schema_4.retConsStatServ.TConsStatServ;
import br.com.swconsultoria.nfe.schema_4.retConsStatServ.TRetConsStatServ;
import javax.xml.bind.JAXBElement;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ObjectFactory_ESTest extends ObjectFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ObjectFactory objectFactory0 = new ObjectFactory();
      TRetConsStatServ tRetConsStatServ0 = new TRetConsStatServ();
      JAXBElement<TRetConsStatServ> jAXBElement0 = objectFactory0.createRetConsStatServ(tRetConsStatServ0);
      assertNotNull(jAXBElement0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ObjectFactory objectFactory0 = new ObjectFactory();
      TConsStatServ tConsStatServ0 = objectFactory0.createTConsStatServ();
      assertNull(tConsStatServ0.getTpAmb());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ObjectFactory objectFactory0 = new ObjectFactory();
      TRetConsStatServ tRetConsStatServ0 = objectFactory0.createTRetConsStatServ();
      assertNull(tRetConsStatServ0.getXObs());
  }
}
